// runtime_api.cppm - Compile-time tests for wwr.runtime_api
//
// Every exported wwr* name is the backend's own entity. See gpu_check_macros.h.

module;

#include "gpu_check_macros.h"

export module wwr.test.gpu.runtime_api;

import std;
import wwr.runtime_api;
#if defined(WWR_GPU_BACKEND_CUDA)
import wwr.cuda.cuda_runtime_api;
#else
import wwr.hip.hip_runtime_api;
#endif

namespace wwr::test {

using namespace wwr;

#if defined(WWR_GPU_BACKEND_CUDA)

using namespace wwr::cuda;

// ────────────────────────────────────────────────────────────────────────
// CUDA backend
// ────────────────────────────────────────────────────────────────────────

WWR_SAME_TYPE(wwrError_t, cudaError_t)
WWR_SAME_TYPE(wwrStream_t, cudaStream_t)
WWR_SAME_TYPE(wwrStreamCaptureMode, cudaStreamCaptureMode)
WWR_SAME_TYPE(wwrEvent_t, cudaEvent_t)
WWR_SAME_TYPE(wwrMemPool_t, cudaMemPool_t)
WWR_SAME_TYPE(wwrMemPoolProps, cudaMemPoolProps)
WWR_SAME_TYPE(wwrGraph_t, cudaGraph_t)
WWR_SAME_TYPE(wwrGraphExec_t, cudaGraphExec_t)
WWR_SAME_TYPE(wwrDeviceProp, cudaDeviceProp)

WWR_SAME_VALUE(wwrSuccess, cudaSuccess)
WWR_SAME_VALUE(wwrStreamDefault, cudaStreamDefault)
WWR_SAME_VALUE(wwrStreamNonBlocking, cudaStreamNonBlocking)
WWR_SAME_VALUE(wwrStreamCaptureModeGlobal, cudaStreamCaptureModeGlobal)
WWR_SAME_VALUE(wwrStreamCaptureModeThreadLocal, cudaStreamCaptureModeThreadLocal)
WWR_SAME_VALUE(wwrStreamCaptureModeRelaxed, cudaStreamCaptureModeRelaxed)
WWR_SAME_VALUE(wwrEventDefault, cudaEventDefault)
WWR_SAME_VALUE(wwrEventBlockingSync, cudaEventBlockingSync)
WWR_SAME_VALUE(wwrEventDisableTiming, cudaEventDisableTiming)
WWR_SAME_VALUE(wwrMemAllocationTypePinned, cudaMemAllocationTypePinned)
WWR_SAME_VALUE(wwrMemHandleTypeNone, cudaMemHandleTypeNone)
WWR_SAME_VALUE(wwrMemLocationTypeDevice, cudaMemLocationTypeDevice)
WWR_SAME_VALUE(wwrMemPoolAttrReleaseThreshold, cudaMemPoolAttrReleaseThreshold)

WWR_SAME_FUNCTION(wwrGetErrorName, cudaGetErrorName)
WWR_SAME_FUNCTION(wwrGetErrorString, cudaGetErrorString)
WWR_SAME_FUNCTION(wwrGetDevice, cudaGetDevice)
WWR_SAME_FUNCTION(wwrSetDevice, cudaSetDevice)
WWR_SAME_FUNCTION(wwrGetDeviceProperties, cudaGetDeviceProperties)
WWR_SAME_FUNCTION(wwrStreamCreate, cudaStreamCreate)
WWR_SAME_FUNCTION(wwrStreamCreateWithFlags, cudaStreamCreateWithFlags)
WWR_SAME_FUNCTION(wwrStreamCreateWithPriority, cudaStreamCreateWithPriority)
WWR_SAME_FUNCTION(wwrStreamGetFlags, cudaStreamGetFlags)
WWR_SAME_FUNCTION(wwrStreamWaitEvent, cudaStreamWaitEvent)
WWR_SAME_FUNCTION(wwrStreamSynchronize, cudaStreamSynchronize)
WWR_SAME_FUNCTION(wwrStreamDestroy, cudaStreamDestroy)
WWR_SAME_FUNCTION(wwrStreamBeginCapture, cudaStreamBeginCapture)
WWR_SAME_FUNCTION(wwrStreamEndCapture, cudaStreamEndCapture)
WWR_SAME_FUNCTION(wwrEventCreate, cudaEventCreate)
WWR_SAME_FUNCTION(wwrEventCreateWithFlags, cudaEventCreateWithFlags)
WWR_SAME_FUNCTION(wwrEventRecord, cudaEventRecord)
WWR_SAME_FUNCTION(wwrEventRecordWithFlags, cudaEventRecordWithFlags)
WWR_SAME_FUNCTION(wwrEventSynchronize, cudaEventSynchronize)
WWR_SAME_FUNCTION(wwrEventQuery, cudaEventQuery)
WWR_SAME_FUNCTION(wwrEventDestroy, cudaEventDestroy)
WWR_SAME_FUNCTION(wwrMemPoolCreate, cudaMemPoolCreate)
WWR_SAME_FUNCTION(wwrMemPoolSetAttribute, cudaMemPoolSetAttribute)
WWR_SAME_FUNCTION(wwrMemPoolDestroy, cudaMemPoolDestroy)
WWR_SAME_FUNCTION(wwrGraphCreate, cudaGraphCreate)
WWR_SAME_FUNCTION(wwrGraphDestroy, cudaGraphDestroy)
WWR_SAME_FUNCTION(wwrGraphExecDestroy, cudaGraphExecDestroy)
WWR_SAME_FUNCTION(wwrGraphLaunch, cudaGraphLaunch)
WWR_SAME_FUNCTION(wwrGraphUpload, cudaGraphUpload)
// wwrGraphInstantiate is a hand-written forwarding function (its backend
// signatures diverge), not a plain alias, so &wwrGraphInstantiate is not any
// single backend symbol -- WWR_SAME_FUNCTION does not apply. It is proven by
// compiling (the forward resolves on each backend) and by GpuGraphExecTests.

WWR_SAME_TYPE(wwrMemcpyKind, cudaMemcpyKind)
WWR_SAME_VALUE(wwrMemcpyHostToDevice, cudaMemcpyHostToDevice)
WWR_SAME_VALUE(wwrMemcpyDeviceToHost, cudaMemcpyDeviceToHost)
WWR_SAME_VALUE(wwrMemcpyDeviceToDevice, cudaMemcpyDeviceToDevice)
WWR_SAME_FUNCTION(wwrMalloc, cudaMalloc)
WWR_SAME_FUNCTION(wwrFree, cudaFree)
WWR_SAME_FUNCTION(wwrMemcpy, cudaMemcpy)
WWR_SAME_FUNCTION(wwrMemset, cudaMemset)
WWR_SAME_FUNCTION(wwrDeviceSynchronize, cudaDeviceSynchronize)

WWR_SAME_VALUE(wwrErrorInvalidValue, cudaErrorInvalidValue)

// Shared cudaError_t status codes (the whole cuda∩hip error enum).
WWR_SAME_VALUE(wwrErrorAlreadyAcquired, cudaErrorAlreadyAcquired)
WWR_SAME_VALUE(wwrErrorAlreadyMapped, cudaErrorAlreadyMapped)
WWR_SAME_VALUE(wwrErrorArrayIsMapped, cudaErrorArrayIsMapped)
WWR_SAME_VALUE(wwrErrorAssert, cudaErrorAssert)
WWR_SAME_VALUE(wwrErrorCapturedEvent, cudaErrorCapturedEvent)
WWR_SAME_VALUE(wwrErrorContextIsDestroyed, cudaErrorContextIsDestroyed)
WWR_SAME_VALUE(wwrErrorCooperativeLaunchTooLarge, cudaErrorCooperativeLaunchTooLarge)
WWR_SAME_VALUE(wwrErrorFileNotFound, cudaErrorFileNotFound)
WWR_SAME_VALUE(wwrErrorGraphExecUpdateFailure, cudaErrorGraphExecUpdateFailure)
WWR_SAME_VALUE(wwrErrorHostMemoryAlreadyRegistered, cudaErrorHostMemoryAlreadyRegistered)
WWR_SAME_VALUE(wwrErrorHostMemoryNotRegistered, cudaErrorHostMemoryNotRegistered)
WWR_SAME_VALUE(wwrErrorIllegalAddress, cudaErrorIllegalAddress)
WWR_SAME_VALUE(wwrErrorIllegalState, cudaErrorIllegalState)
WWR_SAME_VALUE(wwrErrorInitializationError, cudaErrorInitializationError)
WWR_SAME_VALUE(wwrErrorInsufficientDriver, cudaErrorInsufficientDriver)
WWR_SAME_VALUE(wwrErrorInvalidChannelDescriptor, cudaErrorInvalidChannelDescriptor)
WWR_SAME_VALUE(wwrErrorInvalidConfiguration, cudaErrorInvalidConfiguration)
WWR_SAME_VALUE(wwrErrorInvalidDevice, cudaErrorInvalidDevice)
WWR_SAME_VALUE(wwrErrorInvalidDeviceFunction, cudaErrorInvalidDeviceFunction)
WWR_SAME_VALUE(wwrErrorInvalidDevicePointer, cudaErrorInvalidDevicePointer)
WWR_SAME_VALUE(wwrErrorInvalidGraphicsContext, cudaErrorInvalidGraphicsContext)
WWR_SAME_VALUE(wwrErrorInvalidMemcpyDirection, cudaErrorInvalidMemcpyDirection)
WWR_SAME_VALUE(wwrErrorInvalidPitchValue, cudaErrorInvalidPitchValue)
WWR_SAME_VALUE(wwrErrorInvalidResourceHandle, cudaErrorInvalidResourceHandle)
WWR_SAME_VALUE(wwrErrorInvalidSource, cudaErrorInvalidSource)
WWR_SAME_VALUE(wwrErrorInvalidSymbol, cudaErrorInvalidSymbol)
WWR_SAME_VALUE(wwrErrorInvalidTexture, cudaErrorInvalidTexture)
WWR_SAME_VALUE(wwrErrorLaunchFailure, cudaErrorLaunchFailure)
WWR_SAME_VALUE(wwrErrorLaunchOutOfResources, cudaErrorLaunchOutOfResources)
WWR_SAME_VALUE(wwrErrorLaunchTimeout, cudaErrorLaunchTimeout)
WWR_SAME_VALUE(wwrErrorMapBufferObjectFailed, cudaErrorMapBufferObjectFailed)
WWR_SAME_VALUE(wwrErrorMemoryAllocation, cudaErrorMemoryAllocation)
WWR_SAME_VALUE(wwrErrorMissingConfiguration, cudaErrorMissingConfiguration)
WWR_SAME_VALUE(wwrErrorNoDevice, cudaErrorNoDevice)
WWR_SAME_VALUE(wwrErrorNotMapped, cudaErrorNotMapped)
WWR_SAME_VALUE(wwrErrorNotMappedAsArray, cudaErrorNotMappedAsArray)
WWR_SAME_VALUE(wwrErrorNotMappedAsPointer, cudaErrorNotMappedAsPointer)
WWR_SAME_VALUE(wwrErrorNotReady, cudaErrorNotReady)
WWR_SAME_VALUE(wwrErrorNotSupported, cudaErrorNotSupported)
WWR_SAME_VALUE(wwrErrorOperatingSystem, cudaErrorOperatingSystem)
WWR_SAME_VALUE(wwrErrorPeerAccessAlreadyEnabled, cudaErrorPeerAccessAlreadyEnabled)
WWR_SAME_VALUE(wwrErrorPeerAccessNotEnabled, cudaErrorPeerAccessNotEnabled)
WWR_SAME_VALUE(wwrErrorPeerAccessUnsupported, cudaErrorPeerAccessUnsupported)
WWR_SAME_VALUE(wwrErrorPriorLaunchFailure, cudaErrorPriorLaunchFailure)
WWR_SAME_VALUE(wwrErrorProfilerAlreadyStarted, cudaErrorProfilerAlreadyStarted)
WWR_SAME_VALUE(wwrErrorProfilerAlreadyStopped, cudaErrorProfilerAlreadyStopped)
WWR_SAME_VALUE(wwrErrorProfilerDisabled, cudaErrorProfilerDisabled)
WWR_SAME_VALUE(wwrErrorProfilerNotInitialized, cudaErrorProfilerNotInitialized)
WWR_SAME_VALUE(wwrErrorSetOnActiveProcess, cudaErrorSetOnActiveProcess)
WWR_SAME_VALUE(wwrErrorSharedObjectInitFailed, cudaErrorSharedObjectInitFailed)
WWR_SAME_VALUE(wwrErrorSharedObjectSymbolNotFound, cudaErrorSharedObjectSymbolNotFound)
WWR_SAME_VALUE(wwrErrorStreamCaptureImplicit, cudaErrorStreamCaptureImplicit)
WWR_SAME_VALUE(wwrErrorStreamCaptureInvalidated, cudaErrorStreamCaptureInvalidated)
WWR_SAME_VALUE(wwrErrorStreamCaptureIsolation, cudaErrorStreamCaptureIsolation)
WWR_SAME_VALUE(wwrErrorStreamCaptureMerge, cudaErrorStreamCaptureMerge)
WWR_SAME_VALUE(wwrErrorStreamCaptureUnjoined, cudaErrorStreamCaptureUnjoined)
WWR_SAME_VALUE(wwrErrorStreamCaptureUnmatched, cudaErrorStreamCaptureUnmatched)
WWR_SAME_VALUE(wwrErrorStreamCaptureUnsupported, cudaErrorStreamCaptureUnsupported)
WWR_SAME_VALUE(wwrErrorStreamCaptureWrongThread, cudaErrorStreamCaptureWrongThread)
WWR_SAME_VALUE(wwrErrorUnknown, cudaErrorUnknown)
WWR_SAME_VALUE(wwrErrorUnsupportedLimit, cudaErrorUnsupportedLimit)
WWR_SAME_FUNCTION(wwrGetLastError, cudaGetLastError)
WWR_SAME_FUNCTION(wwrPeekAtLastError, cudaPeekAtLastError)

WWR_SAME_VALUE(wwrMemcpyDefault, cudaMemcpyDefault)
// wwrMallocAsync / wwrMallocFromPoolAsync are hand-written forwarders, not plain
// aliases: the HIP entry points are overload sets whose template overload the
// disable macro does not suppress, so the wwr* layer forwards rather than binds a
// reference. &wwr* is therefore not a single backend symbol -- WWR_SAME_FUNCTION
// does not apply. Proven by compiling and by GpuMemoryBufferTests / basic.cpp.
WWR_SAME_FUNCTION(wwrFreeAsync, cudaFreeAsync)
WWR_SAME_FUNCTION(wwrMemcpyAsync, cudaMemcpyAsync)
WWR_SAME_FUNCTION(wwrMemsetAsync, cudaMemsetAsync)

WWR_SAME_VALUE(wwrHostAllocDefault, cudaHostAllocDefault)
WWR_SAME_VALUE(wwrHostAllocMapped, cudaHostAllocMapped)
WWR_SAME_VALUE(wwrHostAllocWriteCombined, cudaHostAllocWriteCombined)
WWR_SAME_FUNCTION(wwrHostAlloc, cudaHostAlloc)
WWR_SAME_FUNCTION(wwrFreeHost, cudaFreeHost)

WWR_SAME_VALUE(wwrMemAttachGlobal, cudaMemAttachGlobal)
WWR_SAME_VALUE(wwrMemAttachHost, cudaMemAttachHost)
WWR_SAME_FUNCTION(wwrMallocManaged, cudaMallocManaged)

// Texture and surface objects
WWR_SAME_TYPE(wwrTextureObject_t, cudaTextureObject_t)
WWR_SAME_TYPE(wwrSurfaceObject_t, cudaSurfaceObject_t)
WWR_SAME_TYPE(wwrResourceDesc, cudaResourceDesc)
WWR_SAME_TYPE(wwrTextureDesc, cudaTextureDesc)
WWR_SAME_TYPE(wwrResourceViewDesc, cudaResourceViewDesc)
WWR_SAME_TYPE(wwrChannelFormatDesc, cudaChannelFormatDesc)
WWR_SAME_TYPE(wwrChannelFormatKind, cudaChannelFormatKind)
WWR_SAME_TYPE(wwrResourceType, cudaResourceType)
WWR_SAME_TYPE(wwrArray_t, cudaArray_t)
WWR_SAME_VALUE(wwrChannelFormatKindSigned, cudaChannelFormatKindSigned)
WWR_SAME_VALUE(wwrChannelFormatKindUnsigned, cudaChannelFormatKindUnsigned)
WWR_SAME_VALUE(wwrChannelFormatKindFloat, cudaChannelFormatKindFloat)
WWR_SAME_VALUE(wwrResourceTypeArray, cudaResourceTypeArray)
WWR_SAME_VALUE(wwrResourceTypeLinear, cudaResourceTypeLinear)
WWR_SAME_VALUE(wwrArrayDefault, cudaArrayDefault)
WWR_SAME_VALUE(wwrArraySurfaceLoadStore, cudaArraySurfaceLoadStore)
WWR_SAME_FUNCTION(wwrMallocArray, cudaMallocArray)
WWR_SAME_FUNCTION(wwrFreeArray, cudaFreeArray)
WWR_SAME_FUNCTION(wwrCreateTextureObject, cudaCreateTextureObject)
WWR_SAME_FUNCTION(wwrDestroyTextureObject, cudaDestroyTextureObject)
WWR_SAME_FUNCTION(wwrCreateSurfaceObject, cudaCreateSurfaceObject)
WWR_SAME_FUNCTION(wwrDestroySurfaceObject, cudaDestroySurfaceObject)

// Memory -- alloc/free/copy/set/advise/pool (#260).
WWR_SAME_TYPE(wwrHostFn_t, cudaHostFn_t)
WWR_SAME_TYPE(wwrHostNodeParams, cudaHostNodeParams)
WWR_SAME_TYPE(wwrMemAccessDesc, cudaMemAccessDesc)
WWR_SAME_TYPE(wwrMemAccessFlags, cudaMemAccessFlags)
WWR_SAME_TYPE(wwrMemAllocNodeParams, cudaMemAllocNodeParams)
WWR_SAME_TYPE(wwrMemAllocationHandleType, cudaMemAllocationHandleType)
WWR_SAME_TYPE(wwrMemAllocationType, cudaMemAllocationType)
WWR_SAME_TYPE(wwrMemFreeNodeParams, cudaMemFreeNodeParams)
WWR_SAME_TYPE(wwrMemLocation, cudaMemLocation)
WWR_SAME_TYPE(wwrMemLocationType, cudaMemLocationType)
WWR_SAME_TYPE(wwrMemPoolAttr, cudaMemPoolAttr)
WWR_SAME_TYPE(wwrMemPoolPtrExportData, cudaMemPoolPtrExportData)
WWR_SAME_TYPE(wwrMemRangeAttribute, cudaMemRangeAttribute)
WWR_SAME_TYPE(wwrMemcpy3DBatchOp, cudaMemcpy3DBatchOp)
WWR_SAME_TYPE(wwrMemcpy3DOperand, cudaMemcpy3DOperand)
WWR_SAME_TYPE(wwrMemcpy3DOperandType, cudaMemcpy3DOperandType)
WWR_SAME_TYPE(wwrMemcpy3DParms, cudaMemcpy3DParms)
WWR_SAME_TYPE(wwrMemcpy3DPeerParms, cudaMemcpy3DPeerParms)
WWR_SAME_TYPE(wwrMemcpyAttributes, cudaMemcpyAttributes)
WWR_SAME_TYPE(wwrMemcpyFlags, cudaMemcpyFlags)
WWR_SAME_TYPE(wwrMemcpyNodeParams, cudaMemcpyNodeParams)
WWR_SAME_TYPE(wwrMemcpySrcAccessOrder, cudaMemcpySrcAccessOrder)
WWR_SAME_TYPE(wwrMemoryAdvise, cudaMemoryAdvise)
WWR_SAME_TYPE(wwrMemoryType, cudaMemoryType)
WWR_SAME_TYPE(wwrMemsetParams, cudaMemsetParams)
WWR_SAME_TYPE(wwrPitchedPtr, cudaPitchedPtr)
WWR_SAME_VALUE(wwrMemAccessFlagsProtNone, cudaMemAccessFlagsProtNone)
WWR_SAME_VALUE(wwrMemAccessFlagsProtRead, cudaMemAccessFlagsProtRead)
WWR_SAME_VALUE(wwrMemAccessFlagsProtReadWrite, cudaMemAccessFlagsProtReadWrite)
WWR_SAME_VALUE(wwrMemAdviseSetAccessedBy, cudaMemAdviseSetAccessedBy)
WWR_SAME_VALUE(wwrMemAdviseSetPreferredLocation, cudaMemAdviseSetPreferredLocation)
WWR_SAME_VALUE(wwrMemAdviseSetReadMostly, cudaMemAdviseSetReadMostly)
WWR_SAME_VALUE(wwrMemAdviseUnsetAccessedBy, cudaMemAdviseUnsetAccessedBy)
WWR_SAME_VALUE(wwrMemAdviseUnsetPreferredLocation, cudaMemAdviseUnsetPreferredLocation)
WWR_SAME_VALUE(wwrMemAdviseUnsetReadMostly, cudaMemAdviseUnsetReadMostly)
WWR_SAME_VALUE(wwrMemAllocationTypeInvalid, cudaMemAllocationTypeInvalid)
WWR_SAME_VALUE(wwrMemAllocationTypeMax, cudaMemAllocationTypeMax)
WWR_SAME_VALUE(wwrMemHandleTypePosixFileDescriptor, cudaMemHandleTypePosixFileDescriptor)
WWR_SAME_VALUE(wwrMemHandleTypeWin32, cudaMemHandleTypeWin32)
WWR_SAME_VALUE(wwrMemHandleTypeWin32Kmt, cudaMemHandleTypeWin32Kmt)
WWR_SAME_VALUE(wwrMemLocationTypeHost, cudaMemLocationTypeHost)
WWR_SAME_VALUE(wwrMemLocationTypeHostNuma, cudaMemLocationTypeHostNuma)
WWR_SAME_VALUE(wwrMemLocationTypeHostNumaCurrent, cudaMemLocationTypeHostNumaCurrent)
WWR_SAME_VALUE(wwrMemLocationTypeInvalid, cudaMemLocationTypeInvalid)
WWR_SAME_VALUE(wwrMemLocationTypeNone, cudaMemLocationTypeNone)
WWR_SAME_VALUE(wwrMemPoolAttrReservedMemCurrent, cudaMemPoolAttrReservedMemCurrent)
WWR_SAME_VALUE(wwrMemPoolAttrReservedMemHigh, cudaMemPoolAttrReservedMemHigh)
WWR_SAME_VALUE(wwrMemPoolAttrUsedMemCurrent, cudaMemPoolAttrUsedMemCurrent)
WWR_SAME_VALUE(wwrMemPoolAttrUsedMemHigh, cudaMemPoolAttrUsedMemHigh)
WWR_SAME_VALUE(wwrMemPoolReuseAllowInternalDependencies, cudaMemPoolReuseAllowInternalDependencies)
WWR_SAME_VALUE(wwrMemPoolReuseAllowOpportunistic, cudaMemPoolReuseAllowOpportunistic)
WWR_SAME_VALUE(wwrMemPoolReuseFollowEventDependencies, cudaMemPoolReuseFollowEventDependencies)
WWR_SAME_VALUE(wwrMemRangeAttributeAccessedBy, cudaMemRangeAttributeAccessedBy)
WWR_SAME_VALUE(wwrMemRangeAttributeLastPrefetchLocation, cudaMemRangeAttributeLastPrefetchLocation)
WWR_SAME_VALUE(wwrMemRangeAttributePreferredLocation, cudaMemRangeAttributePreferredLocation)
WWR_SAME_VALUE(wwrMemRangeAttributeReadMostly, cudaMemRangeAttributeReadMostly)
WWR_SAME_VALUE(wwrMemcpyFlagDefault, cudaMemcpyFlagDefault)
WWR_SAME_VALUE(wwrMemcpyFlagPreferOverlapWithCompute, cudaMemcpyFlagPreferOverlapWithCompute)
WWR_SAME_VALUE(wwrMemcpyHostToHost, cudaMemcpyHostToHost)
WWR_SAME_VALUE(wwrMemcpyOperandTypeMax, cudaMemcpyOperandTypeMax)
WWR_SAME_VALUE(wwrMemcpyOperandTypePointer, cudaMemcpyOperandTypePointer)
WWR_SAME_VALUE(wwrMemcpySrcAccessOrderAny, cudaMemcpySrcAccessOrderAny)
WWR_SAME_VALUE(wwrMemcpySrcAccessOrderDuringApiCall, cudaMemcpySrcAccessOrderDuringApiCall)
WWR_SAME_VALUE(wwrMemcpySrcAccessOrderInvalid, cudaMemcpySrcAccessOrderInvalid)
WWR_SAME_VALUE(wwrMemcpySrcAccessOrderMax, cudaMemcpySrcAccessOrderMax)
WWR_SAME_VALUE(wwrMemcpySrcAccessOrderStream, cudaMemcpySrcAccessOrderStream)
WWR_SAME_VALUE(wwrMemoryTypeDevice, cudaMemoryTypeDevice)
WWR_SAME_VALUE(wwrMemoryTypeHost, cudaMemoryTypeHost)
WWR_SAME_VALUE(wwrMemoryTypeManaged, cudaMemoryTypeManaged)
WWR_SAME_VALUE(wwrMemoryTypeUnregistered, cudaMemoryTypeUnregistered)
WWR_SAME_FUNCTION(wwrHostGetDevicePointer, cudaHostGetDevicePointer)
WWR_SAME_FUNCTION(wwrHostGetFlags, cudaHostGetFlags)
WWR_SAME_FUNCTION(wwrHostRegister, cudaHostRegister)
WWR_SAME_FUNCTION(wwrHostUnregister, cudaHostUnregister)
WWR_SAME_FUNCTION(wwrMalloc3D, cudaMalloc3D)
WWR_SAME_FUNCTION(wwrMemAdvise, cudaMemAdvise)
WWR_SAME_FUNCTION(wwrMemGetInfo, cudaMemGetInfo)
WWR_SAME_FUNCTION(wwrMemPoolExportPointer, cudaMemPoolExportPointer)
WWR_SAME_FUNCTION(wwrMemPoolExportToShareableHandle, cudaMemPoolExportToShareableHandle)
WWR_SAME_FUNCTION(wwrMemPoolGetAccess, cudaMemPoolGetAccess)
WWR_SAME_FUNCTION(wwrMemPoolGetAttribute, cudaMemPoolGetAttribute)
WWR_SAME_FUNCTION(wwrMemPoolImportFromShareableHandle, cudaMemPoolImportFromShareableHandle)
WWR_SAME_FUNCTION(wwrMemPoolImportPointer, cudaMemPoolImportPointer)
WWR_SAME_FUNCTION(wwrMemPoolSetAccess, cudaMemPoolSetAccess)
WWR_SAME_FUNCTION(wwrMemPoolTrimTo, cudaMemPoolTrimTo)
WWR_SAME_FUNCTION(wwrMemPrefetchAsync, cudaMemPrefetchAsync)
WWR_SAME_FUNCTION(wwrMemRangeGetAttribute, cudaMemRangeGetAttribute)
WWR_SAME_FUNCTION(wwrMemRangeGetAttributes, cudaMemRangeGetAttributes)
WWR_SAME_FUNCTION(wwrMemcpy2D, cudaMemcpy2D)
WWR_SAME_FUNCTION(wwrMemcpy2DAsync, cudaMemcpy2DAsync)
WWR_SAME_FUNCTION(wwrMemcpy3D, cudaMemcpy3D)
WWR_SAME_FUNCTION(wwrMemcpy3DAsync, cudaMemcpy3DAsync)
WWR_SAME_FUNCTION(wwrMemcpy3DBatchAsync, cudaMemcpy3DBatchAsync)
WWR_SAME_FUNCTION(wwrMemcpy3DPeer, cudaMemcpy3DPeer)
WWR_SAME_FUNCTION(wwrMemcpy3DPeerAsync, cudaMemcpy3DPeerAsync)
WWR_SAME_FUNCTION(wwrMemcpyBatchAsync, cudaMemcpyBatchAsync)
WWR_SAME_FUNCTION(wwrMemcpyPeer, cudaMemcpyPeer)
WWR_SAME_FUNCTION(wwrMemcpyPeerAsync, cudaMemcpyPeerAsync)
WWR_SAME_FUNCTION(wwrMemset2D, cudaMemset2D)
WWR_SAME_FUNCTION(wwrMemset2DAsync, cudaMemset2DAsync)
WWR_SAME_FUNCTION(wwrMemset3D, cudaMemset3D)
WWR_SAME_FUNCTION(wwrMemset3DAsync, cudaMemset3DAsync)
// wwrMallocPitch and wwrMemcpy{To,From}Symbol{,Async} are hand-written
// forwarders (hip* are overload sets), so &wwr* is not a single backend
// symbol -- WWR_SAME_FUNCTION does not apply. Proven by compiling.

// Execution control -- stream/event/launch/occupancy/func (#261).
WWR_SAME_TYPE(wwrEventRecordNodeParams, cudaEventRecordNodeParams)
WWR_SAME_TYPE(wwrEventWaitNodeParams, cudaEventWaitNodeParams)
WWR_SAME_TYPE(wwrFuncAttribute, cudaFuncAttribute)
WWR_SAME_TYPE(wwrFuncAttributes, cudaFuncAttributes)
WWR_SAME_TYPE(wwrFunction_t, cudaFunction_t)
WWR_SAME_TYPE(wwrKernelNodeParams, cudaKernelNodeParams)
WWR_SAME_TYPE(wwrKernel_t, cudaKernel_t)
WWR_SAME_TYPE(wwrLaunchAttribute, cudaLaunchAttribute)
WWR_SAME_TYPE(wwrLaunchAttributeID, cudaLaunchAttributeID)
WWR_SAME_TYPE(wwrLaunchAttributeValue, cudaLaunchAttributeValue)
WWR_SAME_TYPE(wwrLaunchAttribute_st, cudaLaunchAttribute_st)
WWR_SAME_TYPE(wwrLaunchConfig_st, cudaLaunchConfig_st)
WWR_SAME_TYPE(wwrLaunchConfig_t, cudaLaunchConfig_t)
WWR_SAME_TYPE(wwrLaunchMemSyncDomain, cudaLaunchMemSyncDomain)
WWR_SAME_TYPE(wwrLaunchMemSyncDomainMap, cudaLaunchMemSyncDomainMap)
WWR_SAME_TYPE(wwrStreamCallback_t, cudaStreamCallback_t)
WWR_SAME_TYPE(wwrStreamCaptureStatus, cudaStreamCaptureStatus)
WWR_SAME_TYPE(wwrStreamUpdateCaptureDependenciesFlags, cudaStreamUpdateCaptureDependenciesFlags)
WWR_SAME_VALUE(wwrFuncAttributeMax, cudaFuncAttributeMax)
WWR_SAME_VALUE(wwrFuncAttributeMaxDynamicSharedMemorySize, cudaFuncAttributeMaxDynamicSharedMemorySize)
WWR_SAME_VALUE(wwrFuncAttributePreferredSharedMemoryCarveout, cudaFuncAttributePreferredSharedMemoryCarveout)
WWR_SAME_VALUE(wwrFuncCachePreferEqual, cudaFuncCachePreferEqual)
WWR_SAME_VALUE(wwrFuncCachePreferL1, cudaFuncCachePreferL1)
WWR_SAME_VALUE(wwrFuncCachePreferNone, cudaFuncCachePreferNone)
WWR_SAME_VALUE(wwrFuncCachePreferShared, cudaFuncCachePreferShared)
WWR_SAME_VALUE(wwrLaunchAttributeAccessPolicyWindow, cudaLaunchAttributeAccessPolicyWindow)
WWR_SAME_VALUE(wwrLaunchAttributeCooperative, cudaLaunchAttributeCooperative)
WWR_SAME_VALUE(wwrLaunchAttributeMemSyncDomain, cudaLaunchAttributeMemSyncDomain)
WWR_SAME_VALUE(wwrLaunchAttributeMemSyncDomainMap, cudaLaunchAttributeMemSyncDomainMap)
WWR_SAME_VALUE(wwrLaunchAttributePriority, cudaLaunchAttributePriority)
WWR_SAME_VALUE(wwrLaunchAttributeSynchronizationPolicy, cudaLaunchAttributeSynchronizationPolicy)
WWR_SAME_VALUE(wwrLaunchMemSyncDomainDefault, cudaLaunchMemSyncDomainDefault)
WWR_SAME_VALUE(wwrLaunchMemSyncDomainRemote, cudaLaunchMemSyncDomainRemote)
WWR_SAME_VALUE(wwrStreamAddCaptureDependencies, cudaStreamAddCaptureDependencies)
WWR_SAME_VALUE(wwrStreamCaptureStatusActive, cudaStreamCaptureStatusActive)
WWR_SAME_VALUE(wwrStreamCaptureStatusInvalidated, cudaStreamCaptureStatusInvalidated)
WWR_SAME_VALUE(wwrStreamCaptureStatusNone, cudaStreamCaptureStatusNone)
WWR_SAME_VALUE(wwrStreamSetCaptureDependencies, cudaStreamSetCaptureDependencies)
WWR_SAME_FUNCTION(wwrEventElapsedTime, cudaEventElapsedTime)
WWR_SAME_FUNCTION(wwrFuncGetAttributes, cudaFuncGetAttributes)
WWR_SAME_FUNCTION(wwrFuncSetAttribute, cudaFuncSetAttribute)
WWR_SAME_FUNCTION(wwrFuncSetCacheConfig, cudaFuncSetCacheConfig)
WWR_SAME_FUNCTION(wwrLaunchHostFunc, cudaLaunchHostFunc)
WWR_SAME_FUNCTION(wwrLaunchKernel, cudaLaunchKernel)
WWR_SAME_FUNCTION(wwrLaunchKernelExC, cudaLaunchKernelExC)
WWR_SAME_FUNCTION(wwrStreamAddCallback, cudaStreamAddCallback)
WWR_SAME_FUNCTION(wwrStreamAttachMemAsync, cudaStreamAttachMemAsync)
WWR_SAME_FUNCTION(wwrStreamGetAttribute, cudaStreamGetAttribute)
WWR_SAME_FUNCTION(wwrStreamGetCaptureInfo, cudaStreamGetCaptureInfo)
WWR_SAME_FUNCTION(wwrStreamGetDevice, cudaStreamGetDevice)
WWR_SAME_FUNCTION(wwrStreamGetId, cudaStreamGetId)
WWR_SAME_FUNCTION(wwrStreamGetPriority, cudaStreamGetPriority)
WWR_SAME_FUNCTION(wwrStreamIsCapturing, cudaStreamIsCapturing)
WWR_SAME_FUNCTION(wwrStreamQuery, cudaStreamQuery)
WWR_SAME_FUNCTION(wwrStreamSetAttribute, cudaStreamSetAttribute)
WWR_SAME_FUNCTION(wwrStreamUpdateCaptureDependencies, cudaStreamUpdateCaptureDependencies)
// wwrOccupancy* and wwrLaunchCooperativeKernel are hand-written forwarders
// (hipCooperative/Occupancy entry points are overload sets; cooperative-launch
// also diverges in signature), so &wwr* is not a single backend symbol --
// WWR_SAME_FUNCTION does not apply. Proven by compiling.

#else

// ────────────────────────────────────────────────────────────────────────
// HIP backend
// ────────────────────────────────────────────────────────────────────────

using namespace wwr::hip;

WWR_SAME_TYPE(wwrError_t, hipError_t)
WWR_SAME_TYPE(wwrStream_t, hipStream_t)
WWR_SAME_TYPE(wwrStreamCaptureMode, hipStreamCaptureMode)
WWR_SAME_TYPE(wwrEvent_t, hipEvent_t)
WWR_SAME_TYPE(wwrMemPool_t, hipMemPool_t)
WWR_SAME_TYPE(wwrMemPoolProps, hipMemPoolProps)
WWR_SAME_TYPE(wwrGraph_t, hipGraph_t)
WWR_SAME_TYPE(wwrGraphExec_t, hipGraphExec_t)
WWR_SAME_TYPE(wwrDeviceProp, hipDeviceProp_tR0600)

WWR_SAME_VALUE(wwrSuccess, hipSuccess)
WWR_SAME_VALUE(wwrStreamDefault, hipStreamDefault)
WWR_SAME_VALUE(wwrStreamNonBlocking, hipStreamNonBlocking)
WWR_SAME_VALUE(wwrStreamCaptureModeGlobal, hipStreamCaptureModeGlobal)
WWR_SAME_VALUE(wwrStreamCaptureModeThreadLocal, hipStreamCaptureModeThreadLocal)
WWR_SAME_VALUE(wwrStreamCaptureModeRelaxed, hipStreamCaptureModeRelaxed)
WWR_SAME_VALUE(wwrEventDefault, hipEventDefault)
WWR_SAME_VALUE(wwrEventBlockingSync, hipEventBlockingSync)
WWR_SAME_VALUE(wwrEventDisableTiming, hipEventDisableTiming)
WWR_SAME_VALUE(wwrMemAllocationTypePinned, hipMemAllocationTypePinned)
WWR_SAME_VALUE(wwrMemHandleTypeNone, hipMemHandleTypeNone)
WWR_SAME_VALUE(wwrMemLocationTypeDevice, hipMemLocationTypeDevice)
WWR_SAME_VALUE(wwrMemPoolAttrReleaseThreshold, hipMemPoolAttrReleaseThreshold)

WWR_SAME_FUNCTION(wwrGetErrorName, hipGetErrorName)
WWR_SAME_FUNCTION(wwrGetErrorString, hipGetErrorString)
WWR_SAME_FUNCTION(wwrGetDevice, hipGetDevice)
WWR_SAME_FUNCTION(wwrSetDevice, hipSetDevice)
WWR_SAME_FUNCTION(wwrGetDeviceProperties, hipGetDevicePropertiesR0600)
WWR_SAME_FUNCTION(wwrStreamCreate, hipStreamCreate)
WWR_SAME_FUNCTION(wwrStreamCreateWithFlags, hipStreamCreateWithFlags)
WWR_SAME_FUNCTION(wwrStreamCreateWithPriority, hipStreamCreateWithPriority)
WWR_SAME_FUNCTION(wwrStreamGetFlags, hipStreamGetFlags)
WWR_SAME_FUNCTION(wwrStreamWaitEvent, hipStreamWaitEvent)
WWR_SAME_FUNCTION(wwrStreamSynchronize, hipStreamSynchronize)
WWR_SAME_FUNCTION(wwrStreamDestroy, hipStreamDestroy)
WWR_SAME_FUNCTION(wwrStreamBeginCapture, hipStreamBeginCapture)
WWR_SAME_FUNCTION(wwrStreamEndCapture, hipStreamEndCapture)
WWR_SAME_FUNCTION(wwrEventCreate, hipEventCreate)
WWR_SAME_FUNCTION(wwrEventCreateWithFlags, hipEventCreateWithFlags)
WWR_SAME_FUNCTION(wwrEventRecord, hipEventRecord)
WWR_SAME_FUNCTION(wwrEventRecordWithFlags, hipEventRecordWithFlags)
WWR_SAME_FUNCTION(wwrEventSynchronize, hipEventSynchronize)
WWR_SAME_FUNCTION(wwrEventQuery, hipEventQuery)
WWR_SAME_FUNCTION(wwrEventDestroy, hipEventDestroy)
WWR_SAME_FUNCTION(wwrMemPoolCreate, hipMemPoolCreate)
WWR_SAME_FUNCTION(wwrMemPoolSetAttribute, hipMemPoolSetAttribute)
WWR_SAME_FUNCTION(wwrMemPoolDestroy, hipMemPoolDestroy)
WWR_SAME_FUNCTION(wwrGraphCreate, hipGraphCreate)
WWR_SAME_FUNCTION(wwrGraphDestroy, hipGraphDestroy)
WWR_SAME_FUNCTION(wwrGraphExecDestroy, hipGraphExecDestroy)
WWR_SAME_FUNCTION(wwrGraphLaunch, hipGraphLaunch)
WWR_SAME_FUNCTION(wwrGraphUpload, hipGraphUpload)
// wwrGraphInstantiate forwards to hipGraphInstantiateWithFlags here (CUDA maps
// to cudaGraphInstantiate); as a hand-written forwarding function it is not a
// single backend symbol, so WWR_SAME_FUNCTION does not apply. Proven by
// compiling and by GpuGraphExecTests.

WWR_SAME_TYPE(wwrMemcpyKind, hipMemcpyKind)
WWR_SAME_VALUE(wwrMemcpyHostToDevice, hipMemcpyHostToDevice)
WWR_SAME_VALUE(wwrMemcpyDeviceToHost, hipMemcpyDeviceToHost)
WWR_SAME_VALUE(wwrMemcpyDeviceToDevice, hipMemcpyDeviceToDevice)
// hipMalloc is an overload set (plus a template<class T> hipMalloc(T**, size_t));
// wwrMalloc must be its void** overload.
static_assert(&wwrMalloc == static_cast<hipError_t (*)(void **, std::size_t)>(&hipMalloc),
              "wwrMalloc is not hipMalloc(void**, size_t)");
WWR_LINK_CHECK(wwrMalloc)
WWR_SAME_FUNCTION(wwrFree, hipFree)
WWR_SAME_FUNCTION(wwrMemcpy, hipMemcpy)
WWR_SAME_FUNCTION(wwrMemset, hipMemset)
WWR_SAME_FUNCTION(wwrDeviceSynchronize, hipDeviceSynchronize)

WWR_SAME_VALUE(wwrErrorInvalidValue, hipErrorInvalidValue)

// Shared hipError_t status codes (the whole cuda∩hip error enum).
WWR_SAME_VALUE(wwrErrorAlreadyAcquired, hipErrorAlreadyAcquired)
WWR_SAME_VALUE(wwrErrorAlreadyMapped, hipErrorAlreadyMapped)
WWR_SAME_VALUE(wwrErrorArrayIsMapped, hipErrorArrayIsMapped)
WWR_SAME_VALUE(wwrErrorAssert, hipErrorAssert)
WWR_SAME_VALUE(wwrErrorCapturedEvent, hipErrorCapturedEvent)
WWR_SAME_VALUE(wwrErrorContextIsDestroyed, hipErrorContextIsDestroyed)
WWR_SAME_VALUE(wwrErrorCooperativeLaunchTooLarge, hipErrorCooperativeLaunchTooLarge)
WWR_SAME_VALUE(wwrErrorFileNotFound, hipErrorFileNotFound)
WWR_SAME_VALUE(wwrErrorGraphExecUpdateFailure, hipErrorGraphExecUpdateFailure)
WWR_SAME_VALUE(wwrErrorHostMemoryAlreadyRegistered, hipErrorHostMemoryAlreadyRegistered)
WWR_SAME_VALUE(wwrErrorHostMemoryNotRegistered, hipErrorHostMemoryNotRegistered)
WWR_SAME_VALUE(wwrErrorIllegalAddress, hipErrorIllegalAddress)
WWR_SAME_VALUE(wwrErrorIllegalState, hipErrorIllegalState)
WWR_SAME_VALUE(wwrErrorInitializationError, hipErrorInitializationError)
WWR_SAME_VALUE(wwrErrorInsufficientDriver, hipErrorInsufficientDriver)
WWR_SAME_VALUE(wwrErrorInvalidChannelDescriptor, hipErrorInvalidChannelDescriptor)
WWR_SAME_VALUE(wwrErrorInvalidConfiguration, hipErrorInvalidConfiguration)
WWR_SAME_VALUE(wwrErrorInvalidDevice, hipErrorInvalidDevice)
WWR_SAME_VALUE(wwrErrorInvalidDeviceFunction, hipErrorInvalidDeviceFunction)
WWR_SAME_VALUE(wwrErrorInvalidDevicePointer, hipErrorInvalidDevicePointer)
WWR_SAME_VALUE(wwrErrorInvalidGraphicsContext, hipErrorInvalidGraphicsContext)
WWR_SAME_VALUE(wwrErrorInvalidMemcpyDirection, hipErrorInvalidMemcpyDirection)
WWR_SAME_VALUE(wwrErrorInvalidPitchValue, hipErrorInvalidPitchValue)
WWR_SAME_VALUE(wwrErrorInvalidResourceHandle, hipErrorInvalidResourceHandle)
WWR_SAME_VALUE(wwrErrorInvalidSource, hipErrorInvalidSource)
WWR_SAME_VALUE(wwrErrorInvalidSymbol, hipErrorInvalidSymbol)
WWR_SAME_VALUE(wwrErrorInvalidTexture, hipErrorInvalidTexture)
WWR_SAME_VALUE(wwrErrorLaunchFailure, hipErrorLaunchFailure)
WWR_SAME_VALUE(wwrErrorLaunchOutOfResources, hipErrorLaunchOutOfResources)
WWR_SAME_VALUE(wwrErrorLaunchTimeout, hipErrorLaunchTimeOut)
WWR_SAME_VALUE(wwrErrorMapBufferObjectFailed, hipErrorMapBufferObjectFailed)
WWR_SAME_VALUE(wwrErrorMemoryAllocation, hipErrorMemoryAllocation)
WWR_SAME_VALUE(wwrErrorMissingConfiguration, hipErrorMissingConfiguration)
WWR_SAME_VALUE(wwrErrorNoDevice, hipErrorNoDevice)
WWR_SAME_VALUE(wwrErrorNotMapped, hipErrorNotMapped)
WWR_SAME_VALUE(wwrErrorNotMappedAsArray, hipErrorNotMappedAsArray)
WWR_SAME_VALUE(wwrErrorNotMappedAsPointer, hipErrorNotMappedAsPointer)
WWR_SAME_VALUE(wwrErrorNotReady, hipErrorNotReady)
WWR_SAME_VALUE(wwrErrorNotSupported, hipErrorNotSupported)
WWR_SAME_VALUE(wwrErrorOperatingSystem, hipErrorOperatingSystem)
WWR_SAME_VALUE(wwrErrorPeerAccessAlreadyEnabled, hipErrorPeerAccessAlreadyEnabled)
WWR_SAME_VALUE(wwrErrorPeerAccessNotEnabled, hipErrorPeerAccessNotEnabled)
WWR_SAME_VALUE(wwrErrorPeerAccessUnsupported, hipErrorPeerAccessUnsupported)
WWR_SAME_VALUE(wwrErrorPriorLaunchFailure, hipErrorPriorLaunchFailure)
WWR_SAME_VALUE(wwrErrorProfilerAlreadyStarted, hipErrorProfilerAlreadyStarted)
WWR_SAME_VALUE(wwrErrorProfilerAlreadyStopped, hipErrorProfilerAlreadyStopped)
WWR_SAME_VALUE(wwrErrorProfilerDisabled, hipErrorProfilerDisabled)
WWR_SAME_VALUE(wwrErrorProfilerNotInitialized, hipErrorProfilerNotInitialized)
WWR_SAME_VALUE(wwrErrorSetOnActiveProcess, hipErrorSetOnActiveProcess)
WWR_SAME_VALUE(wwrErrorSharedObjectInitFailed, hipErrorSharedObjectInitFailed)
WWR_SAME_VALUE(wwrErrorSharedObjectSymbolNotFound, hipErrorSharedObjectSymbolNotFound)
WWR_SAME_VALUE(wwrErrorStreamCaptureImplicit, hipErrorStreamCaptureImplicit)
WWR_SAME_VALUE(wwrErrorStreamCaptureInvalidated, hipErrorStreamCaptureInvalidated)
WWR_SAME_VALUE(wwrErrorStreamCaptureIsolation, hipErrorStreamCaptureIsolation)
WWR_SAME_VALUE(wwrErrorStreamCaptureMerge, hipErrorStreamCaptureMerge)
WWR_SAME_VALUE(wwrErrorStreamCaptureUnjoined, hipErrorStreamCaptureUnjoined)
WWR_SAME_VALUE(wwrErrorStreamCaptureUnmatched, hipErrorStreamCaptureUnmatched)
WWR_SAME_VALUE(wwrErrorStreamCaptureUnsupported, hipErrorStreamCaptureUnsupported)
WWR_SAME_VALUE(wwrErrorStreamCaptureWrongThread, hipErrorStreamCaptureWrongThread)
WWR_SAME_VALUE(wwrErrorUnknown, hipErrorUnknown)
WWR_SAME_VALUE(wwrErrorUnsupportedLimit, hipErrorUnsupportedLimit)
WWR_SAME_FUNCTION(wwrGetLastError, hipGetLastError)
WWR_SAME_FUNCTION(wwrPeekAtLastError, hipPeekAtLastError)

WWR_SAME_VALUE(wwrMemcpyDefault, hipMemcpyDefault)
// wwrMallocAsync / wwrMallocFromPoolAsync are hand-written forwarders, not plain
// aliases: hipMallocAsync / hipMallocFromPoolAsync are overload sets whose
// template<class T> (T**, ...) overload __HIP_DISABLE_CPP_FUNCTIONS__ does not
// suppress (unlike hipMalloc's), so the wwr* layer forwards rather than binds a
// reference. &wwr* is therefore not a single backend symbol -- WWR_SAME_FUNCTION
// does not apply. Proven by compiling and by GpuMemoryBufferTests / basic.cpp.
WWR_SAME_FUNCTION(wwrFreeAsync, hipFreeAsync)
WWR_SAME_FUNCTION(wwrMemcpyAsync, hipMemcpyAsync)
WWR_SAME_FUNCTION(wwrMemsetAsync, hipMemsetAsync)

// hip_runtime_api.h's flag macros are hipHostMalloc*; hipHostAlloc* are
// equal-valued aliases.
WWR_SAME_VALUE(wwrHostAllocDefault, hipHostMallocDefault)
WWR_SAME_VALUE(wwrHostAllocMapped, hipHostMallocMapped)
WWR_SAME_VALUE(wwrHostAllocWriteCombined, hipHostMallocWriteCombined)
// hipHostAlloc and hipMallocManaged are overload sets like hipMalloc; the gpu
// names must be their void** overloads.
static_assert(&wwrHostAlloc ==
                  static_cast<hipError_t (*)(void **, std::size_t, unsigned int)>(&hipHostAlloc),
              "wwrHostAlloc is not hipHostAlloc(void**, size_t, unsigned)");
WWR_LINK_CHECK(wwrHostAlloc)
WWR_SAME_FUNCTION(wwrFreeHost, hipFreeHost)

WWR_SAME_VALUE(wwrMemAttachGlobal, hipMemAttachGlobal)
WWR_SAME_VALUE(wwrMemAttachHost, hipMemAttachHost)
static_assert(&wwrMallocManaged == static_cast<hipError_t (*)(void **, std::size_t, unsigned int)>(
                                       &hipMallocManaged),
              "wwrMallocManaged is not hipMallocManaged(void**, size_t, unsigned)");
WWR_LINK_CHECK(wwrMallocManaged)

// Texture and surface objects
WWR_SAME_TYPE(wwrTextureObject_t, hipTextureObject_t)
WWR_SAME_TYPE(wwrSurfaceObject_t, hipSurfaceObject_t)
WWR_SAME_TYPE(wwrResourceDesc, hipResourceDesc)
WWR_SAME_TYPE(wwrTextureDesc, hipTextureDesc)
WWR_SAME_TYPE(wwrResourceViewDesc, hipResourceViewDesc)
WWR_SAME_TYPE(wwrChannelFormatDesc, hipChannelFormatDesc)
WWR_SAME_TYPE(wwrChannelFormatKind, hipChannelFormatKind)
WWR_SAME_TYPE(wwrResourceType, hipResourceType)
WWR_SAME_TYPE(wwrArray_t, hipArray_t)
WWR_SAME_VALUE(wwrChannelFormatKindSigned, hipChannelFormatKindSigned)
WWR_SAME_VALUE(wwrChannelFormatKindUnsigned, hipChannelFormatKindUnsigned)
WWR_SAME_VALUE(wwrChannelFormatKindFloat, hipChannelFormatKindFloat)
WWR_SAME_VALUE(wwrResourceTypeArray, hipResourceTypeArray)
WWR_SAME_VALUE(wwrResourceTypeLinear, hipResourceTypeLinear)
WWR_SAME_VALUE(wwrArrayDefault, hipArrayDefault)
WWR_SAME_VALUE(wwrArraySurfaceLoadStore, hipArraySurfaceLoadStore)
WWR_SAME_FUNCTION(wwrMallocArray, hipMallocArray)
WWR_SAME_FUNCTION(wwrFreeArray, hipFreeArray)
WWR_SAME_FUNCTION(wwrCreateTextureObject, hipCreateTextureObject)
WWR_SAME_FUNCTION(wwrDestroyTextureObject, hipDestroyTextureObject)
WWR_SAME_FUNCTION(wwrCreateSurfaceObject, hipCreateSurfaceObject)
WWR_SAME_FUNCTION(wwrDestroySurfaceObject, hipDestroySurfaceObject)

// Memory -- alloc/free/copy/set/advise/pool (#260).
WWR_SAME_TYPE(wwrHostFn_t, hipHostFn_t)
WWR_SAME_TYPE(wwrHostNodeParams, hipHostNodeParams)
WWR_SAME_TYPE(wwrMemAccessDesc, hipMemAccessDesc)
WWR_SAME_TYPE(wwrMemAccessFlags, hipMemAccessFlags)
WWR_SAME_TYPE(wwrMemAllocNodeParams, hipMemAllocNodeParams)
WWR_SAME_TYPE(wwrMemAllocationHandleType, hipMemAllocationHandleType)
WWR_SAME_TYPE(wwrMemAllocationType, hipMemAllocationType)
WWR_SAME_TYPE(wwrMemFreeNodeParams, hipMemFreeNodeParams)
WWR_SAME_TYPE(wwrMemLocation, hipMemLocation)
WWR_SAME_TYPE(wwrMemLocationType, hipMemLocationType)
WWR_SAME_TYPE(wwrMemPoolAttr, hipMemPoolAttr)
WWR_SAME_TYPE(wwrMemPoolPtrExportData, hipMemPoolPtrExportData)
WWR_SAME_TYPE(wwrMemRangeAttribute, hipMemRangeAttribute)
WWR_SAME_TYPE(wwrMemcpy3DBatchOp, hipMemcpy3DBatchOp)
WWR_SAME_TYPE(wwrMemcpy3DOperand, hipMemcpy3DOperand)
WWR_SAME_TYPE(wwrMemcpy3DOperandType, hipMemcpy3DOperandType)
WWR_SAME_TYPE(wwrMemcpy3DParms, hipMemcpy3DParms)
WWR_SAME_TYPE(wwrMemcpy3DPeerParms, hipMemcpy3DPeerParms)
WWR_SAME_TYPE(wwrMemcpyAttributes, hipMemcpyAttributes)
WWR_SAME_TYPE(wwrMemcpyFlags, hipMemcpyFlags)
WWR_SAME_TYPE(wwrMemcpyNodeParams, hipMemcpyNodeParams)
WWR_SAME_TYPE(wwrMemcpySrcAccessOrder, hipMemcpySrcAccessOrder)
WWR_SAME_TYPE(wwrMemoryAdvise, hipMemoryAdvise)
WWR_SAME_TYPE(wwrMemoryType, hipMemoryType)
WWR_SAME_TYPE(wwrMemsetParams, hipMemsetParams)
WWR_SAME_TYPE(wwrPitchedPtr, hipPitchedPtr)
WWR_SAME_VALUE(wwrMemAccessFlagsProtNone, hipMemAccessFlagsProtNone)
WWR_SAME_VALUE(wwrMemAccessFlagsProtRead, hipMemAccessFlagsProtRead)
WWR_SAME_VALUE(wwrMemAccessFlagsProtReadWrite, hipMemAccessFlagsProtReadWrite)
WWR_SAME_VALUE(wwrMemAdviseSetAccessedBy, hipMemAdviseSetAccessedBy)
WWR_SAME_VALUE(wwrMemAdviseSetPreferredLocation, hipMemAdviseSetPreferredLocation)
WWR_SAME_VALUE(wwrMemAdviseSetReadMostly, hipMemAdviseSetReadMostly)
WWR_SAME_VALUE(wwrMemAdviseUnsetAccessedBy, hipMemAdviseUnsetAccessedBy)
WWR_SAME_VALUE(wwrMemAdviseUnsetPreferredLocation, hipMemAdviseUnsetPreferredLocation)
WWR_SAME_VALUE(wwrMemAdviseUnsetReadMostly, hipMemAdviseUnsetReadMostly)
WWR_SAME_VALUE(wwrMemAllocationTypeInvalid, hipMemAllocationTypeInvalid)
WWR_SAME_VALUE(wwrMemAllocationTypeMax, hipMemAllocationTypeMax)
WWR_SAME_VALUE(wwrMemHandleTypePosixFileDescriptor, hipMemHandleTypePosixFileDescriptor)
WWR_SAME_VALUE(wwrMemHandleTypeWin32, hipMemHandleTypeWin32)
WWR_SAME_VALUE(wwrMemHandleTypeWin32Kmt, hipMemHandleTypeWin32Kmt)
WWR_SAME_VALUE(wwrMemLocationTypeHost, hipMemLocationTypeHost)
WWR_SAME_VALUE(wwrMemLocationTypeHostNuma, hipMemLocationTypeHostNuma)
WWR_SAME_VALUE(wwrMemLocationTypeHostNumaCurrent, hipMemLocationTypeHostNumaCurrent)
WWR_SAME_VALUE(wwrMemLocationTypeInvalid, hipMemLocationTypeInvalid)
WWR_SAME_VALUE(wwrMemLocationTypeNone, hipMemLocationTypeNone)
WWR_SAME_VALUE(wwrMemPoolAttrReservedMemCurrent, hipMemPoolAttrReservedMemCurrent)
WWR_SAME_VALUE(wwrMemPoolAttrReservedMemHigh, hipMemPoolAttrReservedMemHigh)
WWR_SAME_VALUE(wwrMemPoolAttrUsedMemCurrent, hipMemPoolAttrUsedMemCurrent)
WWR_SAME_VALUE(wwrMemPoolAttrUsedMemHigh, hipMemPoolAttrUsedMemHigh)
WWR_SAME_VALUE(wwrMemPoolReuseAllowInternalDependencies, hipMemPoolReuseAllowInternalDependencies)
WWR_SAME_VALUE(wwrMemPoolReuseAllowOpportunistic, hipMemPoolReuseAllowOpportunistic)
WWR_SAME_VALUE(wwrMemPoolReuseFollowEventDependencies, hipMemPoolReuseFollowEventDependencies)
WWR_SAME_VALUE(wwrMemRangeAttributeAccessedBy, hipMemRangeAttributeAccessedBy)
WWR_SAME_VALUE(wwrMemRangeAttributeLastPrefetchLocation, hipMemRangeAttributeLastPrefetchLocation)
WWR_SAME_VALUE(wwrMemRangeAttributePreferredLocation, hipMemRangeAttributePreferredLocation)
WWR_SAME_VALUE(wwrMemRangeAttributeReadMostly, hipMemRangeAttributeReadMostly)
WWR_SAME_VALUE(wwrMemcpyFlagDefault, hipMemcpyFlagDefault)
WWR_SAME_VALUE(wwrMemcpyFlagPreferOverlapWithCompute, hipMemcpyFlagPreferOverlapWithCompute)
WWR_SAME_VALUE(wwrMemcpyHostToHost, hipMemcpyHostToHost)
WWR_SAME_VALUE(wwrMemcpyOperandTypeMax, hipMemcpyOperandTypeMax)
WWR_SAME_VALUE(wwrMemcpyOperandTypePointer, hipMemcpyOperandTypePointer)
WWR_SAME_VALUE(wwrMemcpySrcAccessOrderAny, hipMemcpySrcAccessOrderAny)
WWR_SAME_VALUE(wwrMemcpySrcAccessOrderDuringApiCall, hipMemcpySrcAccessOrderDuringApiCall)
WWR_SAME_VALUE(wwrMemcpySrcAccessOrderInvalid, hipMemcpySrcAccessOrderInvalid)
WWR_SAME_VALUE(wwrMemcpySrcAccessOrderMax, hipMemcpySrcAccessOrderMax)
WWR_SAME_VALUE(wwrMemcpySrcAccessOrderStream, hipMemcpySrcAccessOrderStream)
WWR_SAME_VALUE(wwrMemoryTypeDevice, hipMemoryTypeDevice)
WWR_SAME_VALUE(wwrMemoryTypeHost, hipMemoryTypeHost)
WWR_SAME_VALUE(wwrMemoryTypeManaged, hipMemoryTypeManaged)
WWR_SAME_VALUE(wwrMemoryTypeUnregistered, hipMemoryTypeUnregistered)
WWR_SAME_FUNCTION(wwrHostGetDevicePointer, hipHostGetDevicePointer)
WWR_SAME_FUNCTION(wwrHostGetFlags, hipHostGetFlags)
WWR_SAME_FUNCTION(wwrHostRegister, hipHostRegister)
WWR_SAME_FUNCTION(wwrHostUnregister, hipHostUnregister)
WWR_SAME_FUNCTION(wwrMalloc3D, hipMalloc3D)
WWR_SAME_FUNCTION(wwrMemAdvise, hipMemAdvise)
WWR_SAME_FUNCTION(wwrMemGetInfo, hipMemGetInfo)
WWR_SAME_FUNCTION(wwrMemPoolExportPointer, hipMemPoolExportPointer)
WWR_SAME_FUNCTION(wwrMemPoolExportToShareableHandle, hipMemPoolExportToShareableHandle)
WWR_SAME_FUNCTION(wwrMemPoolGetAccess, hipMemPoolGetAccess)
WWR_SAME_FUNCTION(wwrMemPoolGetAttribute, hipMemPoolGetAttribute)
WWR_SAME_FUNCTION(wwrMemPoolImportFromShareableHandle, hipMemPoolImportFromShareableHandle)
WWR_SAME_FUNCTION(wwrMemPoolImportPointer, hipMemPoolImportPointer)
WWR_SAME_FUNCTION(wwrMemPoolSetAccess, hipMemPoolSetAccess)
WWR_SAME_FUNCTION(wwrMemPoolTrimTo, hipMemPoolTrimTo)
WWR_SAME_FUNCTION(wwrMemPrefetchAsync, hipMemPrefetchAsync)
WWR_SAME_FUNCTION(wwrMemRangeGetAttribute, hipMemRangeGetAttribute)
WWR_SAME_FUNCTION(wwrMemRangeGetAttributes, hipMemRangeGetAttributes)
WWR_SAME_FUNCTION(wwrMemcpy2D, hipMemcpy2D)
WWR_SAME_FUNCTION(wwrMemcpy2DAsync, hipMemcpy2DAsync)
WWR_SAME_FUNCTION(wwrMemcpy3D, hipMemcpy3D)
WWR_SAME_FUNCTION(wwrMemcpy3DAsync, hipMemcpy3DAsync)
WWR_SAME_FUNCTION(wwrMemcpy3DBatchAsync, hipMemcpy3DBatchAsync)
WWR_SAME_FUNCTION(wwrMemcpy3DPeer, hipMemcpy3DPeer)
WWR_SAME_FUNCTION(wwrMemcpy3DPeerAsync, hipMemcpy3DPeerAsync)
WWR_SAME_FUNCTION(wwrMemcpyBatchAsync, hipMemcpyBatchAsync)
WWR_SAME_FUNCTION(wwrMemcpyPeer, hipMemcpyPeer)
WWR_SAME_FUNCTION(wwrMemcpyPeerAsync, hipMemcpyPeerAsync)
WWR_SAME_FUNCTION(wwrMemset2D, hipMemset2D)
WWR_SAME_FUNCTION(wwrMemset2DAsync, hipMemset2DAsync)
WWR_SAME_FUNCTION(wwrMemset3D, hipMemset3D)
WWR_SAME_FUNCTION(wwrMemset3DAsync, hipMemset3DAsync)
// wwrMallocPitch and wwrMemcpy{To,From}Symbol{,Async} are hand-written
// forwarders (hip* are overload sets), so &wwr* is not a single backend
// symbol -- WWR_SAME_FUNCTION does not apply. Proven by compiling.

// Execution control -- stream/event/launch/occupancy/func (#261).
WWR_SAME_TYPE(wwrEventRecordNodeParams, hipEventRecordNodeParams)
WWR_SAME_TYPE(wwrEventWaitNodeParams, hipEventWaitNodeParams)
WWR_SAME_TYPE(wwrFuncAttribute, hipFuncAttribute)
WWR_SAME_TYPE(wwrFuncAttributes, hipFuncAttributes)
WWR_SAME_TYPE(wwrFunction_t, hipFunction_t)
WWR_SAME_TYPE(wwrKernelNodeParams, hipKernelNodeParams)
WWR_SAME_TYPE(wwrKernel_t, hipKernel_t)
WWR_SAME_TYPE(wwrLaunchAttribute, hipLaunchAttribute)
WWR_SAME_TYPE(wwrLaunchAttributeID, hipLaunchAttributeID)
WWR_SAME_TYPE(wwrLaunchAttributeValue, hipLaunchAttributeValue)
WWR_SAME_TYPE(wwrLaunchAttribute_st, hipLaunchAttribute_st)
WWR_SAME_TYPE(wwrLaunchConfig_st, hipLaunchConfig_st)
WWR_SAME_TYPE(wwrLaunchConfig_t, hipLaunchConfig_t)
WWR_SAME_TYPE(wwrLaunchMemSyncDomain, hipLaunchMemSyncDomain)
WWR_SAME_TYPE(wwrLaunchMemSyncDomainMap, hipLaunchMemSyncDomainMap)
WWR_SAME_TYPE(wwrStreamCallback_t, hipStreamCallback_t)
WWR_SAME_TYPE(wwrStreamCaptureStatus, hipStreamCaptureStatus)
WWR_SAME_TYPE(wwrStreamUpdateCaptureDependenciesFlags, hipStreamUpdateCaptureDependenciesFlags)
WWR_SAME_VALUE(wwrFuncAttributeMax, hipFuncAttributeMax)
WWR_SAME_VALUE(wwrFuncAttributeMaxDynamicSharedMemorySize, hipFuncAttributeMaxDynamicSharedMemorySize)
WWR_SAME_VALUE(wwrFuncAttributePreferredSharedMemoryCarveout, hipFuncAttributePreferredSharedMemoryCarveout)
WWR_SAME_VALUE(wwrFuncCachePreferEqual, hipFuncCachePreferEqual)
WWR_SAME_VALUE(wwrFuncCachePreferL1, hipFuncCachePreferL1)
WWR_SAME_VALUE(wwrFuncCachePreferNone, hipFuncCachePreferNone)
WWR_SAME_VALUE(wwrFuncCachePreferShared, hipFuncCachePreferShared)
WWR_SAME_VALUE(wwrLaunchAttributeAccessPolicyWindow, hipLaunchAttributeAccessPolicyWindow)
WWR_SAME_VALUE(wwrLaunchAttributeCooperative, hipLaunchAttributeCooperative)
WWR_SAME_VALUE(wwrLaunchAttributeMemSyncDomain, hipLaunchAttributeMemSyncDomain)
WWR_SAME_VALUE(wwrLaunchAttributeMemSyncDomainMap, hipLaunchAttributeMemSyncDomainMap)
WWR_SAME_VALUE(wwrLaunchAttributePriority, hipLaunchAttributePriority)
WWR_SAME_VALUE(wwrLaunchAttributeSynchronizationPolicy, hipLaunchAttributeSynchronizationPolicy)
WWR_SAME_VALUE(wwrLaunchMemSyncDomainDefault, hipLaunchMemSyncDomainDefault)
WWR_SAME_VALUE(wwrLaunchMemSyncDomainRemote, hipLaunchMemSyncDomainRemote)
WWR_SAME_VALUE(wwrStreamAddCaptureDependencies, hipStreamAddCaptureDependencies)
WWR_SAME_VALUE(wwrStreamCaptureStatusActive, hipStreamCaptureStatusActive)
WWR_SAME_VALUE(wwrStreamCaptureStatusInvalidated, hipStreamCaptureStatusInvalidated)
WWR_SAME_VALUE(wwrStreamCaptureStatusNone, hipStreamCaptureStatusNone)
WWR_SAME_VALUE(wwrStreamSetCaptureDependencies, hipStreamSetCaptureDependencies)
WWR_SAME_FUNCTION(wwrEventElapsedTime, hipEventElapsedTime)
WWR_SAME_FUNCTION(wwrFuncGetAttributes, hipFuncGetAttributes)
WWR_SAME_FUNCTION(wwrFuncSetAttribute, hipFuncSetAttribute)
WWR_SAME_FUNCTION(wwrFuncSetCacheConfig, hipFuncSetCacheConfig)
WWR_SAME_FUNCTION(wwrLaunchHostFunc, hipLaunchHostFunc)
WWR_SAME_FUNCTION(wwrLaunchKernel, hipLaunchKernel)
WWR_SAME_FUNCTION(wwrLaunchKernelExC, hipLaunchKernelExC)
WWR_SAME_FUNCTION(wwrStreamAddCallback, hipStreamAddCallback)
WWR_SAME_FUNCTION(wwrStreamAttachMemAsync, hipStreamAttachMemAsync)
WWR_SAME_FUNCTION(wwrStreamGetAttribute, hipStreamGetAttribute)
WWR_SAME_FUNCTION(wwrStreamGetCaptureInfo, hipStreamGetCaptureInfo)
WWR_SAME_FUNCTION(wwrStreamGetDevice, hipStreamGetDevice)
WWR_SAME_FUNCTION(wwrStreamGetId, hipStreamGetId)
WWR_SAME_FUNCTION(wwrStreamGetPriority, hipStreamGetPriority)
WWR_SAME_FUNCTION(wwrStreamIsCapturing, hipStreamIsCapturing)
WWR_SAME_FUNCTION(wwrStreamQuery, hipStreamQuery)
WWR_SAME_FUNCTION(wwrStreamSetAttribute, hipStreamSetAttribute)
WWR_SAME_FUNCTION(wwrStreamUpdateCaptureDependencies, hipStreamUpdateCaptureDependencies)
// wwrOccupancy* and wwrLaunchCooperativeKernel are hand-written forwarders
// (hipCooperative/Occupancy entry points are overload sets; cooperative-launch
// also diverges in signature), so &wwr* is not a single backend symbol --
// WWR_SAME_FUNCTION does not apply. Proven by compiling.

#endif

} // namespace wwr::test
