// tensor.cppm - Compile-time tests for wwr.tensor
//
// Every exported wwrtensor* name is checked against the backend's own entity:
// the same type, the same constant (type and value), the same function (see
// gpu_check_macros.h). The whole host API is listed -- like test/gpu/rand.cppm
// and unlike blas/solver, which sample -- because there is no runtime or
// dispatch test downstream to catch a wrong-but-existing backend name (a real
// contraction needs a device job to run).
//
// Unlike test/gpu/ccl.cppm (NCCL/RCCL share identical spellings, so one block
// suffices) the two backends are checked separately: cuTENSOR and hipTensor are
// independent APIs, so the names differ (cutensor* vs hiptensor*). Enumerator
// VALUES are pinned regardless, since matching names never guarantee matching
// values (docs/architecture.md, sections 1 and 6) -- this is exactly what the
// "not a hipify pair" measurement in src/tensor.cppm rests on.
//
// wwrtensorLoggerSetLevel is a forwarding function, not an alias (cuTENSOR takes
// int32_t, hipTensor an enum), so it is not WWR_SAME_FUNCTION'd; its neutral
// signature is pinned once, for both backends, at the end.

module;

#include "gpu_check_macros.h"

export module wwr.test.gpu.tensor;

import std;
import wwr.tensor;
#if defined(WWR_GPU_BACKEND_CUDA)
import wwr.cuda.cutensor;
#else
import wwr.hip.hiptensor;
#endif

namespace wwr::test {

using namespace wwr;

#if defined(WWR_GPU_BACKEND_CUDA)

using namespace wwr::cuda;

// ────────────────────────────────────────────────────────────────────────
// Types
// ────────────────────────────────────────────────────────────────────────

WWR_SAME_TYPE(wwrtensorHandle_t, cutensorHandle_t)
WWR_SAME_TYPE(wwrtensorTensorDescriptor_t, cutensorTensorDescriptor_t)
WWR_SAME_TYPE(wwrtensorOperationDescriptor_t, cutensorOperationDescriptor_t)
WWR_SAME_TYPE(wwrtensorPlan_t, cutensorPlan_t)
WWR_SAME_TYPE(wwrtensorPlanPreference_t, cutensorPlanPreference_t)
WWR_SAME_TYPE(wwrtensorComputeDescriptor_t, cutensorComputeDescriptor_t)
WWR_SAME_TYPE(wwrtensorDataType_t, cutensorDataType_t)
WWR_SAME_TYPE(wwrtensorStatus_t, cutensorStatus_t)
WWR_SAME_TYPE(wwrtensorOperator_t, cutensorOperator_t)
WWR_SAME_TYPE(wwrtensorAlgo_t, cutensorAlgo_t)
WWR_SAME_TYPE(wwrtensorWorksizePreference_t, cutensorWorksizePreference_t)
WWR_SAME_TYPE(wwrtensorOperationDescriptorAttribute_t, cutensorOperationDescriptorAttribute_t)
WWR_SAME_TYPE(wwrtensorPlanPreferenceAttribute_t, cutensorPlanPreferenceAttribute_t)
WWR_SAME_TYPE(wwrtensorPlanAttribute_t, cutensorPlanAttribute_t)
WWR_SAME_TYPE(wwrtensorAutotuneMode_t, cutensorAutotuneMode_t)
WWR_SAME_TYPE(wwrtensorCacheMode_t, cutensorCacheMode_t)
WWR_SAME_TYPE(wwrtensorJitMode_t, cutensorJitMode_t)
WWR_SAME_TYPE(wwrtensorLoggerCallback_t, cutensorLoggerCallback_t)

// ────────────────────────────────────────────────────────────────────────
// Constants (name AND value pinned per backend)
// ────────────────────────────────────────────────────────────────────────

WWR_SAME_VALUE(WWRTENSOR_R_16F, CUTENSOR_R_16F)
WWR_SAME_VALUE(WWRTENSOR_C_16F, CUTENSOR_C_16F)
WWR_SAME_VALUE(WWRTENSOR_R_16BF, CUTENSOR_R_16BF)
WWR_SAME_VALUE(WWRTENSOR_C_16BF, CUTENSOR_C_16BF)
WWR_SAME_VALUE(WWRTENSOR_R_32F, CUTENSOR_R_32F)
WWR_SAME_VALUE(WWRTENSOR_C_32F, CUTENSOR_C_32F)
WWR_SAME_VALUE(WWRTENSOR_R_64F, CUTENSOR_R_64F)
WWR_SAME_VALUE(WWRTENSOR_C_64F, CUTENSOR_C_64F)
WWR_SAME_VALUE(WWRTENSOR_R_4I, CUTENSOR_R_4I)
WWR_SAME_VALUE(WWRTENSOR_C_4I, CUTENSOR_C_4I)
WWR_SAME_VALUE(WWRTENSOR_R_4U, CUTENSOR_R_4U)
WWR_SAME_VALUE(WWRTENSOR_C_4U, CUTENSOR_C_4U)
WWR_SAME_VALUE(WWRTENSOR_R_8I, CUTENSOR_R_8I)
WWR_SAME_VALUE(WWRTENSOR_C_8I, CUTENSOR_C_8I)
WWR_SAME_VALUE(WWRTENSOR_R_8U, CUTENSOR_R_8U)
WWR_SAME_VALUE(WWRTENSOR_C_8U, CUTENSOR_C_8U)
WWR_SAME_VALUE(WWRTENSOR_R_16I, CUTENSOR_R_16I)
WWR_SAME_VALUE(WWRTENSOR_C_16I, CUTENSOR_C_16I)
WWR_SAME_VALUE(WWRTENSOR_R_16U, CUTENSOR_R_16U)
WWR_SAME_VALUE(WWRTENSOR_C_16U, CUTENSOR_C_16U)
WWR_SAME_VALUE(WWRTENSOR_R_32I, CUTENSOR_R_32I)
WWR_SAME_VALUE(WWRTENSOR_C_32I, CUTENSOR_C_32I)
WWR_SAME_VALUE(WWRTENSOR_R_32U, CUTENSOR_R_32U)
WWR_SAME_VALUE(WWRTENSOR_C_32U, CUTENSOR_C_32U)
WWR_SAME_VALUE(WWRTENSOR_R_64I, CUTENSOR_R_64I)
WWR_SAME_VALUE(WWRTENSOR_C_64I, CUTENSOR_C_64I)
WWR_SAME_VALUE(WWRTENSOR_R_64U, CUTENSOR_R_64U)
WWR_SAME_VALUE(WWRTENSOR_C_64U, CUTENSOR_C_64U)
WWR_SAME_VALUE(WWRTENSOR_OP_IDENTITY, CUTENSOR_OP_IDENTITY)
WWR_SAME_VALUE(WWRTENSOR_OP_SQRT, CUTENSOR_OP_SQRT)
WWR_SAME_VALUE(WWRTENSOR_OP_RELU, CUTENSOR_OP_RELU)
WWR_SAME_VALUE(WWRTENSOR_OP_CONJ, CUTENSOR_OP_CONJ)
WWR_SAME_VALUE(WWRTENSOR_OP_RCP, CUTENSOR_OP_RCP)
WWR_SAME_VALUE(WWRTENSOR_OP_SIGMOID, CUTENSOR_OP_SIGMOID)
WWR_SAME_VALUE(WWRTENSOR_OP_TANH, CUTENSOR_OP_TANH)
WWR_SAME_VALUE(WWRTENSOR_OP_EXP, CUTENSOR_OP_EXP)
WWR_SAME_VALUE(WWRTENSOR_OP_LOG, CUTENSOR_OP_LOG)
WWR_SAME_VALUE(WWRTENSOR_OP_ABS, CUTENSOR_OP_ABS)
WWR_SAME_VALUE(WWRTENSOR_OP_NEG, CUTENSOR_OP_NEG)
WWR_SAME_VALUE(WWRTENSOR_OP_SIN, CUTENSOR_OP_SIN)
WWR_SAME_VALUE(WWRTENSOR_OP_COS, CUTENSOR_OP_COS)
WWR_SAME_VALUE(WWRTENSOR_OP_TAN, CUTENSOR_OP_TAN)
WWR_SAME_VALUE(WWRTENSOR_OP_SINH, CUTENSOR_OP_SINH)
WWR_SAME_VALUE(WWRTENSOR_OP_COSH, CUTENSOR_OP_COSH)
WWR_SAME_VALUE(WWRTENSOR_OP_ASIN, CUTENSOR_OP_ASIN)
WWR_SAME_VALUE(WWRTENSOR_OP_ACOS, CUTENSOR_OP_ACOS)
WWR_SAME_VALUE(WWRTENSOR_OP_ATAN, CUTENSOR_OP_ATAN)
WWR_SAME_VALUE(WWRTENSOR_OP_ASINH, CUTENSOR_OP_ASINH)
WWR_SAME_VALUE(WWRTENSOR_OP_ACOSH, CUTENSOR_OP_ACOSH)
WWR_SAME_VALUE(WWRTENSOR_OP_ATANH, CUTENSOR_OP_ATANH)
WWR_SAME_VALUE(WWRTENSOR_OP_CEIL, CUTENSOR_OP_CEIL)
WWR_SAME_VALUE(WWRTENSOR_OP_FLOOR, CUTENSOR_OP_FLOOR)
WWR_SAME_VALUE(WWRTENSOR_OP_ADD, CUTENSOR_OP_ADD)
WWR_SAME_VALUE(WWRTENSOR_OP_MUL, CUTENSOR_OP_MUL)
WWR_SAME_VALUE(WWRTENSOR_OP_MAX, CUTENSOR_OP_MAX)
WWR_SAME_VALUE(WWRTENSOR_OP_MIN, CUTENSOR_OP_MIN)
WWR_SAME_VALUE(WWRTENSOR_OP_UNKNOWN, CUTENSOR_OP_UNKNOWN)
WWR_SAME_VALUE(WWRTENSOR_STATUS_SUCCESS, CUTENSOR_STATUS_SUCCESS)
WWR_SAME_VALUE(WWRTENSOR_STATUS_NOT_INITIALIZED, CUTENSOR_STATUS_NOT_INITIALIZED)
WWR_SAME_VALUE(WWRTENSOR_STATUS_ALLOC_FAILED, CUTENSOR_STATUS_ALLOC_FAILED)
WWR_SAME_VALUE(WWRTENSOR_STATUS_INVALID_VALUE, CUTENSOR_STATUS_INVALID_VALUE)
WWR_SAME_VALUE(WWRTENSOR_STATUS_ARCH_MISMATCH, CUTENSOR_STATUS_ARCH_MISMATCH)
WWR_SAME_VALUE(WWRTENSOR_STATUS_EXECUTION_FAILED, CUTENSOR_STATUS_EXECUTION_FAILED)
WWR_SAME_VALUE(WWRTENSOR_STATUS_INTERNAL_ERROR, CUTENSOR_STATUS_INTERNAL_ERROR)
WWR_SAME_VALUE(WWRTENSOR_STATUS_NOT_SUPPORTED, CUTENSOR_STATUS_NOT_SUPPORTED)
WWR_SAME_VALUE(WWRTENSOR_STATUS_INSUFFICIENT_WORKSPACE, CUTENSOR_STATUS_INSUFFICIENT_WORKSPACE)
WWR_SAME_VALUE(WWRTENSOR_STATUS_INSUFFICIENT_DRIVER, CUTENSOR_STATUS_INSUFFICIENT_DRIVER)
WWR_SAME_VALUE(WWRTENSOR_STATUS_IO_ERROR, CUTENSOR_STATUS_IO_ERROR)
WWR_SAME_VALUE(WWRTENSOR_ALGO_DEFAULT, CUTENSOR_ALGO_DEFAULT)
WWR_SAME_VALUE(WWRTENSOR_ALGO_DEFAULT_PATIENT, CUTENSOR_ALGO_DEFAULT_PATIENT)
WWR_SAME_VALUE(WWRTENSOR_WORKSPACE_MIN, CUTENSOR_WORKSPACE_MIN)
WWR_SAME_VALUE(WWRTENSOR_WORKSPACE_DEFAULT, CUTENSOR_WORKSPACE_DEFAULT)
WWR_SAME_VALUE(WWRTENSOR_WORKSPACE_MAX, CUTENSOR_WORKSPACE_MAX)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_TAG, CUTENSOR_OPERATION_DESCRIPTOR_TAG)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_SCALAR_TYPE, CUTENSOR_OPERATION_DESCRIPTOR_SCALAR_TYPE)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_FLOPS, CUTENSOR_OPERATION_DESCRIPTOR_FLOPS)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_MOVED_BYTES, CUTENSOR_OPERATION_DESCRIPTOR_MOVED_BYTES)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_PADDING_LEFT, CUTENSOR_OPERATION_DESCRIPTOR_PADDING_LEFT)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_PADDING_RIGHT, CUTENSOR_OPERATION_DESCRIPTOR_PADDING_RIGHT)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_PADDING_VALUE, CUTENSOR_OPERATION_DESCRIPTOR_PADDING_VALUE)
WWR_SAME_VALUE(WWRTENSOR_PLAN_PREFERENCE_AUTOTUNE_MODE, CUTENSOR_PLAN_PREFERENCE_AUTOTUNE_MODE)
WWR_SAME_VALUE(WWRTENSOR_PLAN_PREFERENCE_CACHE_MODE, CUTENSOR_PLAN_PREFERENCE_CACHE_MODE)
WWR_SAME_VALUE(WWRTENSOR_PLAN_PREFERENCE_INCREMENTAL_COUNT, CUTENSOR_PLAN_PREFERENCE_INCREMENTAL_COUNT)
WWR_SAME_VALUE(WWRTENSOR_PLAN_PREFERENCE_ALGO, CUTENSOR_PLAN_PREFERENCE_ALGO)
WWR_SAME_VALUE(WWRTENSOR_PLAN_PREFERENCE_KERNEL_RANK, CUTENSOR_PLAN_PREFERENCE_KERNEL_RANK)
WWR_SAME_VALUE(WWRTENSOR_PLAN_PREFERENCE_JIT, CUTENSOR_PLAN_PREFERENCE_JIT)
WWR_SAME_VALUE(WWRTENSOR_PLAN_REQUIRED_WORKSPACE, CUTENSOR_PLAN_REQUIRED_WORKSPACE)
WWR_SAME_VALUE(WWRTENSOR_AUTOTUNE_MODE_NONE, CUTENSOR_AUTOTUNE_MODE_NONE)
WWR_SAME_VALUE(WWRTENSOR_AUTOTUNE_MODE_INCREMENTAL, CUTENSOR_AUTOTUNE_MODE_INCREMENTAL)
WWR_SAME_VALUE(WWRTENSOR_CACHE_MODE_NONE, CUTENSOR_CACHE_MODE_NONE)
WWR_SAME_VALUE(WWRTENSOR_CACHE_MODE_PEDANTIC, CUTENSOR_CACHE_MODE_PEDANTIC)
WWR_SAME_VALUE(WWRTENSOR_JIT_MODE_NONE, CUTENSOR_JIT_MODE_NONE)
WWR_SAME_VALUE(WWRTENSOR_JIT_MODE_DEFAULT, CUTENSOR_JIT_MODE_DEFAULT)

// Compute descriptors are extern-const opaque pointers here (runtime
// globals, not constant expressions), so WWR_SAME_VALUE's `==` cannot be
// a constant expression -- pin object identity and type instead.
static_assert(&WWRTENSOR_COMPUTE_DESC_16F == &CUTENSOR_COMPUTE_DESC_16F,
              "WWRTENSOR_COMPUTE_DESC_16F is not CUTENSOR_COMPUTE_DESC_16F");
static_assert(&WWRTENSOR_COMPUTE_DESC_16BF == &CUTENSOR_COMPUTE_DESC_16BF,
              "WWRTENSOR_COMPUTE_DESC_16BF is not CUTENSOR_COMPUTE_DESC_16BF");
static_assert(&WWRTENSOR_COMPUTE_DESC_32F == &CUTENSOR_COMPUTE_DESC_32F,
              "WWRTENSOR_COMPUTE_DESC_32F is not CUTENSOR_COMPUTE_DESC_32F");
static_assert(&WWRTENSOR_COMPUTE_DESC_64F == &CUTENSOR_COMPUTE_DESC_64F,
              "WWRTENSOR_COMPUTE_DESC_64F is not CUTENSOR_COMPUTE_DESC_64F");
WWR_SAME_TYPE(std::remove_cvref_t<decltype(WWRTENSOR_COMPUTE_DESC_32F)>,
                 cutensorComputeDescriptor_t)

// ────────────────────────────────────────────────────────────────────────
// Functions
// ────────────────────────────────────────────────────────────────────────

WWR_SAME_FUNCTION(wwrtensorCreate, cutensorCreate)
WWR_SAME_FUNCTION(wwrtensorDestroy, cutensorDestroy)
WWR_SAME_FUNCTION(wwrtensorGetErrorString, cutensorGetErrorString)
WWR_SAME_FUNCTION(wwrtensorGetVersion, cutensorGetVersion)
WWR_SAME_FUNCTION(wwrtensorHandleResizePlanCache, cutensorHandleResizePlanCache)
WWR_SAME_FUNCTION(wwrtensorHandleWritePlanCacheToFile, cutensorHandleWritePlanCacheToFile)
WWR_SAME_FUNCTION(wwrtensorHandleReadPlanCacheFromFile, cutensorHandleReadPlanCacheFromFile)
WWR_SAME_FUNCTION(wwrtensorWriteKernelCacheToFile, cutensorWriteKernelCacheToFile)
WWR_SAME_FUNCTION(wwrtensorReadKernelCacheFromFile, cutensorReadKernelCacheFromFile)
WWR_SAME_FUNCTION(wwrtensorCreateTensorDescriptor, cutensorCreateTensorDescriptor)
WWR_SAME_FUNCTION(wwrtensorDestroyTensorDescriptor, cutensorDestroyTensorDescriptor)
WWR_SAME_FUNCTION(wwrtensorCreateElementwiseTrinary, cutensorCreateElementwiseTrinary)
WWR_SAME_FUNCTION(wwrtensorCreateElementwiseBinary, cutensorCreateElementwiseBinary)
WWR_SAME_FUNCTION(wwrtensorCreatePermutation, cutensorCreatePermutation)
WWR_SAME_FUNCTION(wwrtensorCreateContraction, cutensorCreateContraction)
WWR_SAME_FUNCTION(wwrtensorCreateReduction, cutensorCreateReduction)
WWR_SAME_FUNCTION(wwrtensorDestroyOperationDescriptor, cutensorDestroyOperationDescriptor)
WWR_SAME_FUNCTION(wwrtensorOperationDescriptorSetAttribute, cutensorOperationDescriptorSetAttribute)
WWR_SAME_FUNCTION(wwrtensorOperationDescriptorGetAttribute, cutensorOperationDescriptorGetAttribute)
WWR_SAME_FUNCTION(wwrtensorCreatePlanPreference, cutensorCreatePlanPreference)
WWR_SAME_FUNCTION(wwrtensorDestroyPlanPreference, cutensorDestroyPlanPreference)
WWR_SAME_FUNCTION(wwrtensorPlanPreferenceSetAttribute, cutensorPlanPreferenceSetAttribute)
WWR_SAME_FUNCTION(wwrtensorEstimateWorkspaceSize, cutensorEstimateWorkspaceSize)
WWR_SAME_FUNCTION(wwrtensorCreatePlan, cutensorCreatePlan)
WWR_SAME_FUNCTION(wwrtensorDestroyPlan, cutensorDestroyPlan)
WWR_SAME_FUNCTION(wwrtensorPlanGetAttribute, cutensorPlanGetAttribute)
WWR_SAME_FUNCTION(wwrtensorElementwiseTrinaryExecute, cutensorElementwiseTrinaryExecute)
WWR_SAME_FUNCTION(wwrtensorElementwiseBinaryExecute, cutensorElementwiseBinaryExecute)
WWR_SAME_FUNCTION(wwrtensorPermute, cutensorPermute)
WWR_SAME_FUNCTION(wwrtensorContract, cutensorContract)
WWR_SAME_FUNCTION(wwrtensorReduce, cutensorReduce)
WWR_SAME_FUNCTION(wwrtensorLoggerSetCallback, cutensorLoggerSetCallback)
WWR_SAME_FUNCTION(wwrtensorLoggerSetFile, cutensorLoggerSetFile)
WWR_SAME_FUNCTION(wwrtensorLoggerOpenFile, cutensorLoggerOpenFile)
WWR_SAME_FUNCTION(wwrtensorLoggerSetMask, cutensorLoggerSetMask)
WWR_SAME_FUNCTION(wwrtensorLoggerForceDisable, cutensorLoggerForceDisable)

#else

using namespace wwr::hip;

// ────────────────────────────────────────────────────────────────────────
// Types
// ────────────────────────────────────────────────────────────────────────

WWR_SAME_TYPE(wwrtensorHandle_t, hiptensorHandle_t)
WWR_SAME_TYPE(wwrtensorTensorDescriptor_t, hiptensorTensorDescriptor_t)
WWR_SAME_TYPE(wwrtensorOperationDescriptor_t, hiptensorOperationDescriptor_t)
WWR_SAME_TYPE(wwrtensorPlan_t, hiptensorPlan_t)
WWR_SAME_TYPE(wwrtensorPlanPreference_t, hiptensorPlanPreference_t)
WWR_SAME_TYPE(wwrtensorComputeDescriptor_t, hiptensorComputeDescriptor_t)
WWR_SAME_TYPE(wwrtensorDataType_t, hiptensorDataType_t)
WWR_SAME_TYPE(wwrtensorStatus_t, hiptensorStatus_t)
WWR_SAME_TYPE(wwrtensorOperator_t, hiptensorOperator_t)
WWR_SAME_TYPE(wwrtensorAlgo_t, hiptensorAlgo_t)
WWR_SAME_TYPE(wwrtensorWorksizePreference_t, hiptensorWorksizePreference_t)
WWR_SAME_TYPE(wwrtensorOperationDescriptorAttribute_t, hiptensorOperationDescriptorAttribute_t)
WWR_SAME_TYPE(wwrtensorPlanPreferenceAttribute_t, hiptensorPlanPreferenceAttribute_t)
WWR_SAME_TYPE(wwrtensorPlanAttribute_t, hiptensorPlanAttribute_t)
WWR_SAME_TYPE(wwrtensorAutotuneMode_t, hiptensorAutotuneMode_t)
WWR_SAME_TYPE(wwrtensorCacheMode_t, hiptensorCacheMode_t)
WWR_SAME_TYPE(wwrtensorJitMode_t, hiptensorJitMode_t)
WWR_SAME_TYPE(wwrtensorLoggerCallback_t, hiptensorLoggerCallback_t)

// ────────────────────────────────────────────────────────────────────────
// Constants (name AND value pinned per backend)
// ────────────────────────────────────────────────────────────────────────

WWR_SAME_VALUE(WWRTENSOR_R_16F, HIPTENSOR_R_16F)
WWR_SAME_VALUE(WWRTENSOR_C_16F, HIPTENSOR_C_16F)
WWR_SAME_VALUE(WWRTENSOR_R_16BF, HIPTENSOR_R_16BF)
WWR_SAME_VALUE(WWRTENSOR_C_16BF, HIPTENSOR_C_16BF)
WWR_SAME_VALUE(WWRTENSOR_R_32F, HIPTENSOR_R_32F)
WWR_SAME_VALUE(WWRTENSOR_C_32F, HIPTENSOR_C_32F)
WWR_SAME_VALUE(WWRTENSOR_R_64F, HIPTENSOR_R_64F)
WWR_SAME_VALUE(WWRTENSOR_C_64F, HIPTENSOR_C_64F)
WWR_SAME_VALUE(WWRTENSOR_R_4I, HIPTENSOR_R_4I)
WWR_SAME_VALUE(WWRTENSOR_C_4I, HIPTENSOR_C_4I)
WWR_SAME_VALUE(WWRTENSOR_R_4U, HIPTENSOR_R_4U)
WWR_SAME_VALUE(WWRTENSOR_C_4U, HIPTENSOR_C_4U)
WWR_SAME_VALUE(WWRTENSOR_R_8I, HIPTENSOR_R_8I)
WWR_SAME_VALUE(WWRTENSOR_C_8I, HIPTENSOR_C_8I)
WWR_SAME_VALUE(WWRTENSOR_R_8U, HIPTENSOR_R_8U)
WWR_SAME_VALUE(WWRTENSOR_C_8U, HIPTENSOR_C_8U)
WWR_SAME_VALUE(WWRTENSOR_R_16I, HIPTENSOR_R_16I)
WWR_SAME_VALUE(WWRTENSOR_C_16I, HIPTENSOR_C_16I)
WWR_SAME_VALUE(WWRTENSOR_R_16U, HIPTENSOR_R_16U)
WWR_SAME_VALUE(WWRTENSOR_C_16U, HIPTENSOR_C_16U)
WWR_SAME_VALUE(WWRTENSOR_R_32I, HIPTENSOR_R_32I)
WWR_SAME_VALUE(WWRTENSOR_C_32I, HIPTENSOR_C_32I)
WWR_SAME_VALUE(WWRTENSOR_R_32U, HIPTENSOR_R_32U)
WWR_SAME_VALUE(WWRTENSOR_C_32U, HIPTENSOR_C_32U)
WWR_SAME_VALUE(WWRTENSOR_R_64I, HIPTENSOR_R_64I)
WWR_SAME_VALUE(WWRTENSOR_C_64I, HIPTENSOR_C_64I)
WWR_SAME_VALUE(WWRTENSOR_R_64U, HIPTENSOR_R_64U)
WWR_SAME_VALUE(WWRTENSOR_C_64U, HIPTENSOR_C_64U)
WWR_SAME_VALUE(WWRTENSOR_OP_IDENTITY, HIPTENSOR_OP_IDENTITY)
WWR_SAME_VALUE(WWRTENSOR_OP_SQRT, HIPTENSOR_OP_SQRT)
WWR_SAME_VALUE(WWRTENSOR_OP_RELU, HIPTENSOR_OP_RELU)
WWR_SAME_VALUE(WWRTENSOR_OP_CONJ, HIPTENSOR_OP_CONJ)
WWR_SAME_VALUE(WWRTENSOR_OP_RCP, HIPTENSOR_OP_RCP)
WWR_SAME_VALUE(WWRTENSOR_OP_SIGMOID, HIPTENSOR_OP_SIGMOID)
WWR_SAME_VALUE(WWRTENSOR_OP_TANH, HIPTENSOR_OP_TANH)
WWR_SAME_VALUE(WWRTENSOR_OP_EXP, HIPTENSOR_OP_EXP)
WWR_SAME_VALUE(WWRTENSOR_OP_LOG, HIPTENSOR_OP_LOG)
WWR_SAME_VALUE(WWRTENSOR_OP_ABS, HIPTENSOR_OP_ABS)
WWR_SAME_VALUE(WWRTENSOR_OP_NEG, HIPTENSOR_OP_NEG)
WWR_SAME_VALUE(WWRTENSOR_OP_SIN, HIPTENSOR_OP_SIN)
WWR_SAME_VALUE(WWRTENSOR_OP_COS, HIPTENSOR_OP_COS)
WWR_SAME_VALUE(WWRTENSOR_OP_TAN, HIPTENSOR_OP_TAN)
WWR_SAME_VALUE(WWRTENSOR_OP_SINH, HIPTENSOR_OP_SINH)
WWR_SAME_VALUE(WWRTENSOR_OP_COSH, HIPTENSOR_OP_COSH)
WWR_SAME_VALUE(WWRTENSOR_OP_ASIN, HIPTENSOR_OP_ASIN)
WWR_SAME_VALUE(WWRTENSOR_OP_ACOS, HIPTENSOR_OP_ACOS)
WWR_SAME_VALUE(WWRTENSOR_OP_ATAN, HIPTENSOR_OP_ATAN)
WWR_SAME_VALUE(WWRTENSOR_OP_ASINH, HIPTENSOR_OP_ASINH)
WWR_SAME_VALUE(WWRTENSOR_OP_ACOSH, HIPTENSOR_OP_ACOSH)
WWR_SAME_VALUE(WWRTENSOR_OP_ATANH, HIPTENSOR_OP_ATANH)
WWR_SAME_VALUE(WWRTENSOR_OP_CEIL, HIPTENSOR_OP_CEIL)
WWR_SAME_VALUE(WWRTENSOR_OP_FLOOR, HIPTENSOR_OP_FLOOR)
WWR_SAME_VALUE(WWRTENSOR_OP_ADD, HIPTENSOR_OP_ADD)
WWR_SAME_VALUE(WWRTENSOR_OP_MUL, HIPTENSOR_OP_MUL)
WWR_SAME_VALUE(WWRTENSOR_OP_MAX, HIPTENSOR_OP_MAX)
WWR_SAME_VALUE(WWRTENSOR_OP_MIN, HIPTENSOR_OP_MIN)
WWR_SAME_VALUE(WWRTENSOR_OP_UNKNOWN, HIPTENSOR_OP_UNKNOWN)
WWR_SAME_VALUE(WWRTENSOR_STATUS_SUCCESS, HIPTENSOR_STATUS_SUCCESS)
WWR_SAME_VALUE(WWRTENSOR_STATUS_NOT_INITIALIZED, HIPTENSOR_STATUS_NOT_INITIALIZED)
WWR_SAME_VALUE(WWRTENSOR_STATUS_ALLOC_FAILED, HIPTENSOR_STATUS_ALLOC_FAILED)
WWR_SAME_VALUE(WWRTENSOR_STATUS_INVALID_VALUE, HIPTENSOR_STATUS_INVALID_VALUE)
WWR_SAME_VALUE(WWRTENSOR_STATUS_ARCH_MISMATCH, HIPTENSOR_STATUS_ARCH_MISMATCH)
WWR_SAME_VALUE(WWRTENSOR_STATUS_EXECUTION_FAILED, HIPTENSOR_STATUS_EXECUTION_FAILED)
WWR_SAME_VALUE(WWRTENSOR_STATUS_INTERNAL_ERROR, HIPTENSOR_STATUS_INTERNAL_ERROR)
WWR_SAME_VALUE(WWRTENSOR_STATUS_NOT_SUPPORTED, HIPTENSOR_STATUS_NOT_SUPPORTED)
WWR_SAME_VALUE(WWRTENSOR_STATUS_INSUFFICIENT_WORKSPACE, HIPTENSOR_STATUS_INSUFFICIENT_WORKSPACE)
WWR_SAME_VALUE(WWRTENSOR_STATUS_INSUFFICIENT_DRIVER, HIPTENSOR_STATUS_INSUFFICIENT_DRIVER)
WWR_SAME_VALUE(WWRTENSOR_STATUS_IO_ERROR, HIPTENSOR_STATUS_IO_ERROR)
WWR_SAME_VALUE(WWRTENSOR_ALGO_DEFAULT, HIPTENSOR_ALGO_DEFAULT)
WWR_SAME_VALUE(WWRTENSOR_ALGO_DEFAULT_PATIENT, HIPTENSOR_ALGO_DEFAULT_PATIENT)
WWR_SAME_VALUE(WWRTENSOR_WORKSPACE_MIN, HIPTENSOR_WORKSPACE_MIN)
WWR_SAME_VALUE(WWRTENSOR_WORKSPACE_DEFAULT, HIPTENSOR_WORKSPACE_DEFAULT)
WWR_SAME_VALUE(WWRTENSOR_WORKSPACE_MAX, HIPTENSOR_WORKSPACE_MAX)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_TAG, HIPTENSOR_OPERATION_DESCRIPTOR_TAG)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_SCALAR_TYPE, HIPTENSOR_OPERATION_DESCRIPTOR_SCALAR_TYPE)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_FLOPS, HIPTENSOR_OPERATION_DESCRIPTOR_FLOPS)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_MOVED_BYTES, HIPTENSOR_OPERATION_DESCRIPTOR_MOVED_BYTES)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_PADDING_LEFT, HIPTENSOR_OPERATION_DESCRIPTOR_PADDING_LEFT)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_PADDING_RIGHT, HIPTENSOR_OPERATION_DESCRIPTOR_PADDING_RIGHT)
WWR_SAME_VALUE(WWRTENSOR_OPERATION_DESCRIPTOR_PADDING_VALUE, HIPTENSOR_OPERATION_DESCRIPTOR_PADDING_VALUE)
WWR_SAME_VALUE(WWRTENSOR_PLAN_PREFERENCE_AUTOTUNE_MODE, HIPTENSOR_PLAN_PREFERENCE_AUTOTUNE_MODE)
WWR_SAME_VALUE(WWRTENSOR_PLAN_PREFERENCE_CACHE_MODE, HIPTENSOR_PLAN_PREFERENCE_CACHE_MODE)
WWR_SAME_VALUE(WWRTENSOR_PLAN_PREFERENCE_INCREMENTAL_COUNT, HIPTENSOR_PLAN_PREFERENCE_INCREMENTAL_COUNT)
WWR_SAME_VALUE(WWRTENSOR_PLAN_PREFERENCE_ALGO, HIPTENSOR_PLAN_PREFERENCE_ALGO)
WWR_SAME_VALUE(WWRTENSOR_PLAN_PREFERENCE_KERNEL_RANK, HIPTENSOR_PLAN_PREFERENCE_KERNEL_RANK)
WWR_SAME_VALUE(WWRTENSOR_PLAN_PREFERENCE_JIT, HIPTENSOR_PLAN_PREFERENCE_JIT)
WWR_SAME_VALUE(WWRTENSOR_PLAN_REQUIRED_WORKSPACE, HIPTENSOR_PLAN_REQUIRED_WORKSPACE)
WWR_SAME_VALUE(WWRTENSOR_AUTOTUNE_MODE_NONE, HIPTENSOR_AUTOTUNE_MODE_NONE)
WWR_SAME_VALUE(WWRTENSOR_AUTOTUNE_MODE_INCREMENTAL, HIPTENSOR_AUTOTUNE_MODE_INCREMENTAL)
WWR_SAME_VALUE(WWRTENSOR_CACHE_MODE_NONE, HIPTENSOR_CACHE_MODE_NONE)
WWR_SAME_VALUE(WWRTENSOR_CACHE_MODE_PEDANTIC, HIPTENSOR_CACHE_MODE_PEDANTIC)
WWR_SAME_VALUE(WWRTENSOR_JIT_MODE_NONE, HIPTENSOR_JIT_MODE_NONE)
WWR_SAME_VALUE(WWRTENSOR_JIT_MODE_DEFAULT, HIPTENSOR_JIT_MODE_DEFAULT)

// Compute descriptors are enum values here -- WWR_SAME_VALUE applies.
WWR_SAME_VALUE(WWRTENSOR_COMPUTE_DESC_16F, HIPTENSOR_COMPUTE_DESC_16F)
WWR_SAME_VALUE(WWRTENSOR_COMPUTE_DESC_16BF, HIPTENSOR_COMPUTE_DESC_16BF)
WWR_SAME_VALUE(WWRTENSOR_COMPUTE_DESC_32F, HIPTENSOR_COMPUTE_DESC_32F)
WWR_SAME_VALUE(WWRTENSOR_COMPUTE_DESC_64F, HIPTENSOR_COMPUTE_DESC_64F)

// ────────────────────────────────────────────────────────────────────────
// Functions
// ────────────────────────────────────────────────────────────────────────

WWR_SAME_FUNCTION(wwrtensorCreate, hiptensorCreate)
WWR_SAME_FUNCTION(wwrtensorDestroy, hiptensorDestroy)
WWR_SAME_FUNCTION(wwrtensorGetErrorString, hiptensorGetErrorString)
WWR_SAME_FUNCTION(wwrtensorGetVersion, hiptensorGetVersion)
WWR_SAME_FUNCTION(wwrtensorHandleResizePlanCache, hiptensorHandleResizePlanCache)
WWR_SAME_FUNCTION(wwrtensorHandleWritePlanCacheToFile, hiptensorHandleWritePlanCacheToFile)
WWR_SAME_FUNCTION(wwrtensorHandleReadPlanCacheFromFile, hiptensorHandleReadPlanCacheFromFile)
WWR_SAME_FUNCTION(wwrtensorWriteKernelCacheToFile, hiptensorWriteKernelCacheToFile)
WWR_SAME_FUNCTION(wwrtensorReadKernelCacheFromFile, hiptensorReadKernelCacheFromFile)
WWR_SAME_FUNCTION(wwrtensorCreateTensorDescriptor, hiptensorCreateTensorDescriptor)
WWR_SAME_FUNCTION(wwrtensorDestroyTensorDescriptor, hiptensorDestroyTensorDescriptor)
WWR_SAME_FUNCTION(wwrtensorCreateElementwiseTrinary, hiptensorCreateElementwiseTrinary)
WWR_SAME_FUNCTION(wwrtensorCreateElementwiseBinary, hiptensorCreateElementwiseBinary)
WWR_SAME_FUNCTION(wwrtensorCreatePermutation, hiptensorCreatePermutation)
WWR_SAME_FUNCTION(wwrtensorCreateContraction, hiptensorCreateContraction)
WWR_SAME_FUNCTION(wwrtensorCreateReduction, hiptensorCreateReduction)
WWR_SAME_FUNCTION(wwrtensorDestroyOperationDescriptor, hiptensorDestroyOperationDescriptor)
WWR_SAME_FUNCTION(wwrtensorOperationDescriptorSetAttribute, hiptensorOperationDescriptorSetAttribute)
WWR_SAME_FUNCTION(wwrtensorOperationDescriptorGetAttribute, hiptensorOperationDescriptorGetAttribute)
WWR_SAME_FUNCTION(wwrtensorCreatePlanPreference, hiptensorCreatePlanPreference)
WWR_SAME_FUNCTION(wwrtensorDestroyPlanPreference, hiptensorDestroyPlanPreference)
WWR_SAME_FUNCTION(wwrtensorPlanPreferenceSetAttribute, hiptensorPlanPreferenceSetAttribute)
WWR_SAME_FUNCTION(wwrtensorEstimateWorkspaceSize, hiptensorEstimateWorkspaceSize)
WWR_SAME_FUNCTION(wwrtensorCreatePlan, hiptensorCreatePlan)
WWR_SAME_FUNCTION(wwrtensorDestroyPlan, hiptensorDestroyPlan)
WWR_SAME_FUNCTION(wwrtensorPlanGetAttribute, hiptensorPlanGetAttribute)
WWR_SAME_FUNCTION(wwrtensorElementwiseTrinaryExecute, hiptensorElementwiseTrinaryExecute)
WWR_SAME_FUNCTION(wwrtensorElementwiseBinaryExecute, hiptensorElementwiseBinaryExecute)
WWR_SAME_FUNCTION(wwrtensorPermute, hiptensorPermute)
WWR_SAME_FUNCTION(wwrtensorContract, hiptensorContract)
WWR_SAME_FUNCTION(wwrtensorReduce, hiptensorReduce)
WWR_SAME_FUNCTION(wwrtensorLoggerSetCallback, hiptensorLoggerSetCallback)
WWR_SAME_FUNCTION(wwrtensorLoggerSetFile, hiptensorLoggerSetFile)
WWR_SAME_FUNCTION(wwrtensorLoggerOpenFile, hiptensorLoggerOpenFile)
WWR_SAME_FUNCTION(wwrtensorLoggerSetMask, hiptensorLoggerSetMask)
WWR_SAME_FUNCTION(wwrtensorLoggerForceDisable, hiptensorLoggerForceDisable)

#endif

// ────────────────────────────────────────────────────────────────────────
// Both backends: wwrtensorLoggerSetLevel takes cuTENSOR's plain int32_t level
// (hipTensor's hiptensorLogLevel_t enum is cast into on the HIP side)
// ────────────────────────────────────────────────────────────────────────

WWR_SAME_TYPE(std::remove_cvref_t<decltype(wwrtensorLoggerSetLevel)>,
                 wwrtensorStatus_t(std::int32_t))

} // namespace wwr::test
