/**
 * @file cublasLt.cppm
 * @brief Primary interface for wwr.cuda.cublasLt
 *
 * This module wraps the native cuBLASLt API and exports types, constants,
 * and functions for the cuBLASLt (lightweight cuBLAS) library.
 *
 * Usage:
 *   import wwr.cuda.cublasLt;
 */

module;

#include <cublasLt.h>

// Validate and undef numeric implementation flag macros before they
// escape into the module's purview.
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_FMA == (0x01ull << 0),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_FMA mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_HMMA == (0x02ull << 0),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_HMMA mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_IMMA == (0x04ull << 0),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_IMMA mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_DMMA == (0x08ull << 0),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_DMMA mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_TENSOR_OP_MASK == (0xfeull << 0),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_TENSOR_OP_MASK mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_OP_TYPE_MASK == (0xffull << 0),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_OP_TYPE_MASK mismatch");

static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_16F == (0x01ull << 8),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_16F mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_32F == (0x02ull << 8),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_32F mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_64F == (0x04ull << 8),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_64F mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_32I == (0x08ull << 8),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_32I mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_TYPE_MASK == (0xffull << 8),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_TYPE_MASK mismatch");

static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_16F == (0x01ull << 16),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_16F mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_16BF == (0x02ull << 16),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_16BF mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_TF32 == (0x04ull << 16),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_TF32 mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_32F == (0x08ull << 16),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_32F mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_64F == (0x10ull << 16),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_64F mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_8I == (0x20ull << 16),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_8I mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_8F_E4M3 == (0x40ull << 16),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_8F_E4M3 mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_8F_E5M2 == (0x80ull << 16),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_8F_E5M2 mismatch");
static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_OP_INPUT_TYPE_MASK == (0xffull << 16),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_OP_INPUT_TYPE_MASK mismatch");

static_assert(CUBLASLT_NUMERICAL_IMPL_FLAGS_GAUSSIAN == (0x01ull << 32),
              "CUBLASLT_NUMERICAL_IMPL_FLAGS_GAUSSIAN mismatch");

#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_FMA
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_HMMA
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_IMMA
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_DMMA
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_TENSOR_OP_MASK
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_OP_TYPE_MASK
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_16F
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_32F
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_64F
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_32I
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_TYPE_MASK
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_16F
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_16BF
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_TF32
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_32F
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_64F
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_8I
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_8F_E4M3
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_8F_E5M2
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_OP_INPUT_TYPE_MASK
#undef CUBLASLT_NUMERICAL_IMPL_FLAGS_GAUSSIAN

export module wwr.cuda.cublasLt;

// ========================================================================
// Export all cuBLASLt types and functions in wwr namespace
// ========================================================================

export namespace wwr::cuda {

// ========================================================================
// Numeric implementation flags (constexpr replacements for macros)
// ========================================================================

inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_FMA = (0x01ull << 0);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_HMMA = (0x02ull << 0);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_IMMA = (0x04ull << 0);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_DMMA = (0x08ull << 0);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_TENSOR_OP_MASK = (0xfeull << 0);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_OP_TYPE_MASK = (0xffull << 0);

inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_16F = (0x01ull << 8);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_32F = (0x02ull << 8);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_64F = (0x04ull << 8);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_32I = (0x08ull << 8);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_ACCUMULATOR_TYPE_MASK =
    (0xffull << 8);

inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_16F = (0x01ull << 16);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_16BF = (0x02ull << 16);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_TF32 = (0x04ull << 16);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_32F = (0x08ull << 16);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_64F = (0x10ull << 16);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_8I = (0x20ull << 16);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_8F_E4M3 = (0x40ull << 16);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_INPUT_8F_E5M2 = (0x80ull << 16);
inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_OP_INPUT_TYPE_MASK =
    (0xffull << 16);

inline constexpr unsigned long long CUBLASLT_NUMERICAL_IMPL_FLAGS_GAUSSIAN = (0x01ull << 32);

// ========================================================================
// Opaque handle types
// ========================================================================
using ::cublasLtHandle_t;

// ========================================================================
// Semi-opaque descriptor types (structs)
// ========================================================================
using ::cublasLtMatmulAlgo_t;
using ::cublasLtMatmulDescOpaque_t;
using ::cublasLtMatmulPreferenceOpaque_t;
using ::cublasLtMatrixLayoutOpaque_t;
using ::cublasLtMatrixTransformDescOpaque_t;

// Opaque pointer-to-struct descriptor types
using ::cublasLtMatmulDesc_t;
using ::cublasLtMatmulPreference_t;
using ::cublasLtMatrixLayout_t;
using ::cublasLtMatrixTransformDesc_t;

// Numerical implementation flags typedef
using ::cublasLtNumericalImplFlags_t;

// ========================================================================
// Re-exported cuBLAS types (from cublas_api.h via cublasLt.h)
// ========================================================================
using ::cublasComputeType_t;
using ::cublasStatus_t;
using ::cudaStream_t;

// ========================================================================
// Enumerations: cublasLtMatmulTile_t
// ========================================================================
using ::CUBLASLT_MATMUL_TILE_104x128;
using ::CUBLASLT_MATMUL_TILE_104x192;
using ::CUBLASLT_MATMUL_TILE_104x256;
using ::CUBLASLT_MATMUL_TILE_104x320;
using ::CUBLASLT_MATMUL_TILE_104x384;
using ::CUBLASLT_MATMUL_TILE_104x448;
using ::CUBLASLT_MATMUL_TILE_104x64;
using ::CUBLASLT_MATMUL_TILE_112x128;
using ::CUBLASLT_MATMUL_TILE_112x192;
using ::CUBLASLT_MATMUL_TILE_112x256;
using ::CUBLASLT_MATMUL_TILE_112x320;
using ::CUBLASLT_MATMUL_TILE_112x384;
using ::CUBLASLT_MATMUL_TILE_112x64;
using ::CUBLASLT_MATMUL_TILE_120x128;
using ::CUBLASLT_MATMUL_TILE_120x192;
using ::CUBLASLT_MATMUL_TILE_120x256;
using ::CUBLASLT_MATMUL_TILE_120x320;
using ::CUBLASLT_MATMUL_TILE_120x384;
using ::CUBLASLT_MATMUL_TILE_120x64;
using ::CUBLASLT_MATMUL_TILE_128x104;
using ::CUBLASLT_MATMUL_TILE_128x112;
using ::CUBLASLT_MATMUL_TILE_128x120;
using ::CUBLASLT_MATMUL_TILE_128x128;
using ::CUBLASLT_MATMUL_TILE_128x136;
using ::CUBLASLT_MATMUL_TILE_128x144;
using ::CUBLASLT_MATMUL_TILE_128x152;
using ::CUBLASLT_MATMUL_TILE_128x16;
using ::CUBLASLT_MATMUL_TILE_128x160;
using ::CUBLASLT_MATMUL_TILE_128x168;
using ::CUBLASLT_MATMUL_TILE_128x176;
using ::CUBLASLT_MATMUL_TILE_128x184;
using ::CUBLASLT_MATMUL_TILE_128x192;
using ::CUBLASLT_MATMUL_TILE_128x200;
using ::CUBLASLT_MATMUL_TILE_128x208;
using ::CUBLASLT_MATMUL_TILE_128x216;
using ::CUBLASLT_MATMUL_TILE_128x224;
using ::CUBLASLT_MATMUL_TILE_128x232;
using ::CUBLASLT_MATMUL_TILE_128x24;
using ::CUBLASLT_MATMUL_TILE_128x240;
using ::CUBLASLT_MATMUL_TILE_128x248;
using ::CUBLASLT_MATMUL_TILE_128x256;
using ::CUBLASLT_MATMUL_TILE_128x264;
using ::CUBLASLT_MATMUL_TILE_128x272;
using ::CUBLASLT_MATMUL_TILE_128x280;
using ::CUBLASLT_MATMUL_TILE_128x288;
using ::CUBLASLT_MATMUL_TILE_128x296;
using ::CUBLASLT_MATMUL_TILE_128x304;
using ::CUBLASLT_MATMUL_TILE_128x312;
using ::CUBLASLT_MATMUL_TILE_128x32;
using ::CUBLASLT_MATMUL_TILE_128x320;
using ::CUBLASLT_MATMUL_TILE_128x328;
using ::CUBLASLT_MATMUL_TILE_128x336;
using ::CUBLASLT_MATMUL_TILE_128x344;
using ::CUBLASLT_MATMUL_TILE_128x352;
using ::CUBLASLT_MATMUL_TILE_128x360;
using ::CUBLASLT_MATMUL_TILE_128x368;
using ::CUBLASLT_MATMUL_TILE_128x376;
using ::CUBLASLT_MATMUL_TILE_128x384;
using ::CUBLASLT_MATMUL_TILE_128x392;
using ::CUBLASLT_MATMUL_TILE_128x40;
using ::CUBLASLT_MATMUL_TILE_128x400;
using ::CUBLASLT_MATMUL_TILE_128x408;
using ::CUBLASLT_MATMUL_TILE_128x416;
using ::CUBLASLT_MATMUL_TILE_128x424;
using ::CUBLASLT_MATMUL_TILE_128x432;
using ::CUBLASLT_MATMUL_TILE_128x440;
using ::CUBLASLT_MATMUL_TILE_128x448;
using ::CUBLASLT_MATMUL_TILE_128x456;
using ::CUBLASLT_MATMUL_TILE_128x464;
using ::CUBLASLT_MATMUL_TILE_128x472;
using ::CUBLASLT_MATMUL_TILE_128x48;
using ::CUBLASLT_MATMUL_TILE_128x480;
using ::CUBLASLT_MATMUL_TILE_128x488;
using ::CUBLASLT_MATMUL_TILE_128x496;
using ::CUBLASLT_MATMUL_TILE_128x504;
using ::CUBLASLT_MATMUL_TILE_128x512;
using ::CUBLASLT_MATMUL_TILE_128x56;
using ::CUBLASLT_MATMUL_TILE_128x64;
using ::CUBLASLT_MATMUL_TILE_128x72;
using ::CUBLASLT_MATMUL_TILE_128x8;
using ::CUBLASLT_MATMUL_TILE_128x80;
using ::CUBLASLT_MATMUL_TILE_128x88;
using ::CUBLASLT_MATMUL_TILE_128x96;
using ::CUBLASLT_MATMUL_TILE_136x128;
using ::CUBLASLT_MATMUL_TILE_136x192;
using ::CUBLASLT_MATMUL_TILE_136x256;
using ::CUBLASLT_MATMUL_TILE_136x320;
using ::CUBLASLT_MATMUL_TILE_136x64;
using ::CUBLASLT_MATMUL_TILE_144x128;
using ::CUBLASLT_MATMUL_TILE_144x192;
using ::CUBLASLT_MATMUL_TILE_144x256;
using ::CUBLASLT_MATMUL_TILE_144x320;
using ::CUBLASLT_MATMUL_TILE_144x64;
using ::CUBLASLT_MATMUL_TILE_152x128;
using ::CUBLASLT_MATMUL_TILE_152x192;
using ::CUBLASLT_MATMUL_TILE_152x256;
using ::CUBLASLT_MATMUL_TILE_152x320;
using ::CUBLASLT_MATMUL_TILE_152x64;
using ::CUBLASLT_MATMUL_TILE_160x128;
using ::CUBLASLT_MATMUL_TILE_160x192;
using ::CUBLASLT_MATMUL_TILE_160x256;
using ::CUBLASLT_MATMUL_TILE_160x64;
using ::CUBLASLT_MATMUL_TILE_168x128;
using ::CUBLASLT_MATMUL_TILE_168x192;
using ::CUBLASLT_MATMUL_TILE_168x256;
using ::CUBLASLT_MATMUL_TILE_168x64;
using ::CUBLASLT_MATMUL_TILE_16x128;
using ::CUBLASLT_MATMUL_TILE_16x16;
using ::CUBLASLT_MATMUL_TILE_16x192;
using ::CUBLASLT_MATMUL_TILE_16x256;
using ::CUBLASLT_MATMUL_TILE_16x32;
using ::CUBLASLT_MATMUL_TILE_16x320;
using ::CUBLASLT_MATMUL_TILE_16x384;
using ::CUBLASLT_MATMUL_TILE_16x448;
using ::CUBLASLT_MATMUL_TILE_16x512;
using ::CUBLASLT_MATMUL_TILE_16x576;
using ::CUBLASLT_MATMUL_TILE_16x64;
using ::CUBLASLT_MATMUL_TILE_16x640;
using ::CUBLASLT_MATMUL_TILE_16x704;
using ::CUBLASLT_MATMUL_TILE_16x768;
using ::CUBLASLT_MATMUL_TILE_16x8;
using ::CUBLASLT_MATMUL_TILE_176x128;
using ::CUBLASLT_MATMUL_TILE_176x192;
using ::CUBLASLT_MATMUL_TILE_176x256;
using ::CUBLASLT_MATMUL_TILE_176x64;
using ::CUBLASLT_MATMUL_TILE_184x128;
using ::CUBLASLT_MATMUL_TILE_184x192;
using ::CUBLASLT_MATMUL_TILE_184x256;
using ::CUBLASLT_MATMUL_TILE_184x64;
using ::CUBLASLT_MATMUL_TILE_192x104;
using ::CUBLASLT_MATMUL_TILE_192x112;
using ::CUBLASLT_MATMUL_TILE_192x120;
using ::CUBLASLT_MATMUL_TILE_192x128;
using ::CUBLASLT_MATMUL_TILE_192x136;
using ::CUBLASLT_MATMUL_TILE_192x144;
using ::CUBLASLT_MATMUL_TILE_192x152;
using ::CUBLASLT_MATMUL_TILE_192x16;
using ::CUBLASLT_MATMUL_TILE_192x160;
using ::CUBLASLT_MATMUL_TILE_192x168;
using ::CUBLASLT_MATMUL_TILE_192x176;
using ::CUBLASLT_MATMUL_TILE_192x184;
using ::CUBLASLT_MATMUL_TILE_192x192;
using ::CUBLASLT_MATMUL_TILE_192x200;
using ::CUBLASLT_MATMUL_TILE_192x208;
using ::CUBLASLT_MATMUL_TILE_192x216;
using ::CUBLASLT_MATMUL_TILE_192x224;
using ::CUBLASLT_MATMUL_TILE_192x232;
using ::CUBLASLT_MATMUL_TILE_192x24;
using ::CUBLASLT_MATMUL_TILE_192x240;
using ::CUBLASLT_MATMUL_TILE_192x248;
using ::CUBLASLT_MATMUL_TILE_192x256;
using ::CUBLASLT_MATMUL_TILE_192x264;
using ::CUBLASLT_MATMUL_TILE_192x272;
using ::CUBLASLT_MATMUL_TILE_192x280;
using ::CUBLASLT_MATMUL_TILE_192x288;
using ::CUBLASLT_MATMUL_TILE_192x296;
using ::CUBLASLT_MATMUL_TILE_192x304;
using ::CUBLASLT_MATMUL_TILE_192x312;
using ::CUBLASLT_MATMUL_TILE_192x32;
using ::CUBLASLT_MATMUL_TILE_192x320;
using ::CUBLASLT_MATMUL_TILE_192x328;
using ::CUBLASLT_MATMUL_TILE_192x336;
using ::CUBLASLT_MATMUL_TILE_192x40;
using ::CUBLASLT_MATMUL_TILE_192x48;
using ::CUBLASLT_MATMUL_TILE_192x56;
using ::CUBLASLT_MATMUL_TILE_192x64;
using ::CUBLASLT_MATMUL_TILE_192x72;
using ::CUBLASLT_MATMUL_TILE_192x8;
using ::CUBLASLT_MATMUL_TILE_192x80;
using ::CUBLASLT_MATMUL_TILE_192x88;
using ::CUBLASLT_MATMUL_TILE_192x96;
using ::CUBLASLT_MATMUL_TILE_200x128;
using ::CUBLASLT_MATMUL_TILE_200x192;
using ::CUBLASLT_MATMUL_TILE_200x64;
using ::CUBLASLT_MATMUL_TILE_208x128;
using ::CUBLASLT_MATMUL_TILE_208x192;
using ::CUBLASLT_MATMUL_TILE_208x64;
using ::CUBLASLT_MATMUL_TILE_216x128;
using ::CUBLASLT_MATMUL_TILE_216x192;
using ::CUBLASLT_MATMUL_TILE_216x64;
using ::CUBLASLT_MATMUL_TILE_224x128;
using ::CUBLASLT_MATMUL_TILE_224x192;
using ::CUBLASLT_MATMUL_TILE_224x64;
using ::CUBLASLT_MATMUL_TILE_232x128;
using ::CUBLASLT_MATMUL_TILE_232x192;
using ::CUBLASLT_MATMUL_TILE_232x64;
using ::CUBLASLT_MATMUL_TILE_240x128;
using ::CUBLASLT_MATMUL_TILE_240x192;
using ::CUBLASLT_MATMUL_TILE_240x64;
using ::CUBLASLT_MATMUL_TILE_248x128;
using ::CUBLASLT_MATMUL_TILE_248x192;
using ::CUBLASLT_MATMUL_TILE_248x64;
using ::CUBLASLT_MATMUL_TILE_24x128;
using ::CUBLASLT_MATMUL_TILE_24x192;
using ::CUBLASLT_MATMUL_TILE_24x256;
using ::CUBLASLT_MATMUL_TILE_24x320;
using ::CUBLASLT_MATMUL_TILE_24x384;
using ::CUBLASLT_MATMUL_TILE_24x448;
using ::CUBLASLT_MATMUL_TILE_24x512;
using ::CUBLASLT_MATMUL_TILE_24x576;
using ::CUBLASLT_MATMUL_TILE_24x64;
using ::CUBLASLT_MATMUL_TILE_24x640;
using ::CUBLASLT_MATMUL_TILE_24x704;
using ::CUBLASLT_MATMUL_TILE_24x768;
using ::CUBLASLT_MATMUL_TILE_256x1024;
using ::CUBLASLT_MATMUL_TILE_256x104;
using ::CUBLASLT_MATMUL_TILE_256x112;
using ::CUBLASLT_MATMUL_TILE_256x120;
using ::CUBLASLT_MATMUL_TILE_256x128;
using ::CUBLASLT_MATMUL_TILE_256x136;
using ::CUBLASLT_MATMUL_TILE_256x144;
using ::CUBLASLT_MATMUL_TILE_256x152;
using ::CUBLASLT_MATMUL_TILE_256x16;
using ::CUBLASLT_MATMUL_TILE_256x160;
using ::CUBLASLT_MATMUL_TILE_256x168;
using ::CUBLASLT_MATMUL_TILE_256x176;
using ::CUBLASLT_MATMUL_TILE_256x184;
using ::CUBLASLT_MATMUL_TILE_256x192;
using ::CUBLASLT_MATMUL_TILE_256x200;
using ::CUBLASLT_MATMUL_TILE_256x208;
using ::CUBLASLT_MATMUL_TILE_256x216;
using ::CUBLASLT_MATMUL_TILE_256x224;
using ::CUBLASLT_MATMUL_TILE_256x232;
using ::CUBLASLT_MATMUL_TILE_256x24;
using ::CUBLASLT_MATMUL_TILE_256x240;
using ::CUBLASLT_MATMUL_TILE_256x248;
using ::CUBLASLT_MATMUL_TILE_256x256;
using ::CUBLASLT_MATMUL_TILE_256x32;
using ::CUBLASLT_MATMUL_TILE_256x40;
using ::CUBLASLT_MATMUL_TILE_256x48;
using ::CUBLASLT_MATMUL_TILE_256x512;
using ::CUBLASLT_MATMUL_TILE_256x56;
using ::CUBLASLT_MATMUL_TILE_256x64;
using ::CUBLASLT_MATMUL_TILE_256x72;
using ::CUBLASLT_MATMUL_TILE_256x8;
using ::CUBLASLT_MATMUL_TILE_256x80;
using ::CUBLASLT_MATMUL_TILE_256x88;
using ::CUBLASLT_MATMUL_TILE_256x96;
using ::CUBLASLT_MATMUL_TILE_264x128;
using ::CUBLASLT_MATMUL_TILE_264x64;
using ::CUBLASLT_MATMUL_TILE_272x128;
using ::CUBLASLT_MATMUL_TILE_272x64;
using ::CUBLASLT_MATMUL_TILE_280x128;
using ::CUBLASLT_MATMUL_TILE_280x64;
using ::CUBLASLT_MATMUL_TILE_288x128;
using ::CUBLASLT_MATMUL_TILE_288x64;
using ::CUBLASLT_MATMUL_TILE_296x128;
using ::CUBLASLT_MATMUL_TILE_296x64;
using ::CUBLASLT_MATMUL_TILE_304x128;
using ::CUBLASLT_MATMUL_TILE_304x64;
using ::CUBLASLT_MATMUL_TILE_312x128;
using ::CUBLASLT_MATMUL_TILE_312x64;
using ::CUBLASLT_MATMUL_TILE_320x104;
using ::CUBLASLT_MATMUL_TILE_320x112;
using ::CUBLASLT_MATMUL_TILE_320x120;
using ::CUBLASLT_MATMUL_TILE_320x128;
using ::CUBLASLT_MATMUL_TILE_320x136;
using ::CUBLASLT_MATMUL_TILE_320x144;
using ::CUBLASLT_MATMUL_TILE_320x152;
using ::CUBLASLT_MATMUL_TILE_320x16;
using ::CUBLASLT_MATMUL_TILE_320x160;
using ::CUBLASLT_MATMUL_TILE_320x168;
using ::CUBLASLT_MATMUL_TILE_320x176;
using ::CUBLASLT_MATMUL_TILE_320x184;
using ::CUBLASLT_MATMUL_TILE_320x192;
using ::CUBLASLT_MATMUL_TILE_320x200;
using ::CUBLASLT_MATMUL_TILE_320x24;
using ::CUBLASLT_MATMUL_TILE_320x32;
using ::CUBLASLT_MATMUL_TILE_320x40;
using ::CUBLASLT_MATMUL_TILE_320x48;
using ::CUBLASLT_MATMUL_TILE_320x56;
using ::CUBLASLT_MATMUL_TILE_320x64;
using ::CUBLASLT_MATMUL_TILE_320x72;
using ::CUBLASLT_MATMUL_TILE_320x8;
using ::CUBLASLT_MATMUL_TILE_320x80;
using ::CUBLASLT_MATMUL_TILE_320x88;
using ::CUBLASLT_MATMUL_TILE_320x96;
using ::CUBLASLT_MATMUL_TILE_328x128;
using ::CUBLASLT_MATMUL_TILE_328x64;
using ::CUBLASLT_MATMUL_TILE_32x128;
using ::CUBLASLT_MATMUL_TILE_32x16;
using ::CUBLASLT_MATMUL_TILE_32x192;
using ::CUBLASLT_MATMUL_TILE_32x256;
using ::CUBLASLT_MATMUL_TILE_32x32;
using ::CUBLASLT_MATMUL_TILE_32x320;
using ::CUBLASLT_MATMUL_TILE_32x384;
using ::CUBLASLT_MATMUL_TILE_32x448;
using ::CUBLASLT_MATMUL_TILE_32x512;
using ::CUBLASLT_MATMUL_TILE_32x576;
using ::CUBLASLT_MATMUL_TILE_32x64;
using ::CUBLASLT_MATMUL_TILE_32x640;
using ::CUBLASLT_MATMUL_TILE_32x704;
using ::CUBLASLT_MATMUL_TILE_32x768;
using ::CUBLASLT_MATMUL_TILE_32x8;
using ::CUBLASLT_MATMUL_TILE_336x128;
using ::CUBLASLT_MATMUL_TILE_336x64;
using ::CUBLASLT_MATMUL_TILE_344x128;
using ::CUBLASLT_MATMUL_TILE_344x64;
using ::CUBLASLT_MATMUL_TILE_352x128;
using ::CUBLASLT_MATMUL_TILE_352x64;
using ::CUBLASLT_MATMUL_TILE_360x128;
using ::CUBLASLT_MATMUL_TILE_360x64;
using ::CUBLASLT_MATMUL_TILE_368x128;
using ::CUBLASLT_MATMUL_TILE_368x64;
using ::CUBLASLT_MATMUL_TILE_376x128;
using ::CUBLASLT_MATMUL_TILE_376x64;
using ::CUBLASLT_MATMUL_TILE_384x104;
using ::CUBLASLT_MATMUL_TILE_384x112;
using ::CUBLASLT_MATMUL_TILE_384x120;
using ::CUBLASLT_MATMUL_TILE_384x128;
using ::CUBLASLT_MATMUL_TILE_384x136;
using ::CUBLASLT_MATMUL_TILE_384x144;
using ::CUBLASLT_MATMUL_TILE_384x152;
using ::CUBLASLT_MATMUL_TILE_384x16;
using ::CUBLASLT_MATMUL_TILE_384x160;
using ::CUBLASLT_MATMUL_TILE_384x168;
using ::CUBLASLT_MATMUL_TILE_384x24;
using ::CUBLASLT_MATMUL_TILE_384x32;
using ::CUBLASLT_MATMUL_TILE_384x40;
using ::CUBLASLT_MATMUL_TILE_384x48;
using ::CUBLASLT_MATMUL_TILE_384x56;
using ::CUBLASLT_MATMUL_TILE_384x64;
using ::CUBLASLT_MATMUL_TILE_384x72;
using ::CUBLASLT_MATMUL_TILE_384x8;
using ::CUBLASLT_MATMUL_TILE_384x80;
using ::CUBLASLT_MATMUL_TILE_384x88;
using ::CUBLASLT_MATMUL_TILE_384x96;
using ::CUBLASLT_MATMUL_TILE_392x64;
using ::CUBLASLT_MATMUL_TILE_400x64;
using ::CUBLASLT_MATMUL_TILE_408x64;
using ::CUBLASLT_MATMUL_TILE_40x128;
using ::CUBLASLT_MATMUL_TILE_40x192;
using ::CUBLASLT_MATMUL_TILE_40x256;
using ::CUBLASLT_MATMUL_TILE_40x320;
using ::CUBLASLT_MATMUL_TILE_40x384;
using ::CUBLASLT_MATMUL_TILE_40x448;
using ::CUBLASLT_MATMUL_TILE_40x512;
using ::CUBLASLT_MATMUL_TILE_40x576;
using ::CUBLASLT_MATMUL_TILE_40x64;
using ::CUBLASLT_MATMUL_TILE_40x640;
using ::CUBLASLT_MATMUL_TILE_40x704;
using ::CUBLASLT_MATMUL_TILE_40x768;
using ::CUBLASLT_MATMUL_TILE_416x64;
using ::CUBLASLT_MATMUL_TILE_424x64;
using ::CUBLASLT_MATMUL_TILE_432x64;
using ::CUBLASLT_MATMUL_TILE_440x64;
using ::CUBLASLT_MATMUL_TILE_448x104;
using ::CUBLASLT_MATMUL_TILE_448x112;
using ::CUBLASLT_MATMUL_TILE_448x120;
using ::CUBLASLT_MATMUL_TILE_448x128;
using ::CUBLASLT_MATMUL_TILE_448x136;
using ::CUBLASLT_MATMUL_TILE_448x144;
using ::CUBLASLT_MATMUL_TILE_448x16;
using ::CUBLASLT_MATMUL_TILE_448x24;
using ::CUBLASLT_MATMUL_TILE_448x32;
using ::CUBLASLT_MATMUL_TILE_448x40;
using ::CUBLASLT_MATMUL_TILE_448x48;
using ::CUBLASLT_MATMUL_TILE_448x56;
using ::CUBLASLT_MATMUL_TILE_448x64;
using ::CUBLASLT_MATMUL_TILE_448x72;
using ::CUBLASLT_MATMUL_TILE_448x8;
using ::CUBLASLT_MATMUL_TILE_448x80;
using ::CUBLASLT_MATMUL_TILE_448x88;
using ::CUBLASLT_MATMUL_TILE_448x96;
using ::CUBLASLT_MATMUL_TILE_456x64;
using ::CUBLASLT_MATMUL_TILE_464x64;
using ::CUBLASLT_MATMUL_TILE_472x64;
using ::CUBLASLT_MATMUL_TILE_480x64;
using ::CUBLASLT_MATMUL_TILE_488x64;
using ::CUBLASLT_MATMUL_TILE_48x128;
using ::CUBLASLT_MATMUL_TILE_48x192;
using ::CUBLASLT_MATMUL_TILE_48x256;
using ::CUBLASLT_MATMUL_TILE_48x320;
using ::CUBLASLT_MATMUL_TILE_48x384;
using ::CUBLASLT_MATMUL_TILE_48x448;
using ::CUBLASLT_MATMUL_TILE_48x512;
using ::CUBLASLT_MATMUL_TILE_48x576;
using ::CUBLASLT_MATMUL_TILE_48x64;
using ::CUBLASLT_MATMUL_TILE_48x640;
using ::CUBLASLT_MATMUL_TILE_48x704;
using ::CUBLASLT_MATMUL_TILE_48x768;
using ::CUBLASLT_MATMUL_TILE_496x64;
using ::CUBLASLT_MATMUL_TILE_504x64;
using ::CUBLASLT_MATMUL_TILE_512x1024;
using ::CUBLASLT_MATMUL_TILE_512x104;
using ::CUBLASLT_MATMUL_TILE_512x112;
using ::CUBLASLT_MATMUL_TILE_512x120;
using ::CUBLASLT_MATMUL_TILE_512x128;
using ::CUBLASLT_MATMUL_TILE_512x16;
using ::CUBLASLT_MATMUL_TILE_512x24;
using ::CUBLASLT_MATMUL_TILE_512x32;
using ::CUBLASLT_MATMUL_TILE_512x40;
using ::CUBLASLT_MATMUL_TILE_512x48;
using ::CUBLASLT_MATMUL_TILE_512x512;
using ::CUBLASLT_MATMUL_TILE_512x56;
using ::CUBLASLT_MATMUL_TILE_512x64;
using ::CUBLASLT_MATMUL_TILE_512x72;
using ::CUBLASLT_MATMUL_TILE_512x8;
using ::CUBLASLT_MATMUL_TILE_512x80;
using ::CUBLASLT_MATMUL_TILE_512x88;
using ::CUBLASLT_MATMUL_TILE_512x96;
using ::CUBLASLT_MATMUL_TILE_520x64;
using ::CUBLASLT_MATMUL_TILE_528x64;
using ::CUBLASLT_MATMUL_TILE_536x64;
using ::CUBLASLT_MATMUL_TILE_544x64;
using ::CUBLASLT_MATMUL_TILE_552x64;
using ::CUBLASLT_MATMUL_TILE_560x64;
using ::CUBLASLT_MATMUL_TILE_568x64;
using ::CUBLASLT_MATMUL_TILE_56x128;
using ::CUBLASLT_MATMUL_TILE_56x192;
using ::CUBLASLT_MATMUL_TILE_56x256;
using ::CUBLASLT_MATMUL_TILE_56x320;
using ::CUBLASLT_MATMUL_TILE_56x384;
using ::CUBLASLT_MATMUL_TILE_56x448;
using ::CUBLASLT_MATMUL_TILE_56x512;
using ::CUBLASLT_MATMUL_TILE_56x576;
using ::CUBLASLT_MATMUL_TILE_56x64;
using ::CUBLASLT_MATMUL_TILE_56x640;
using ::CUBLASLT_MATMUL_TILE_56x704;
using ::CUBLASLT_MATMUL_TILE_56x768;
using ::CUBLASLT_MATMUL_TILE_576x104;
using ::CUBLASLT_MATMUL_TILE_576x112;
using ::CUBLASLT_MATMUL_TILE_576x16;
using ::CUBLASLT_MATMUL_TILE_576x24;
using ::CUBLASLT_MATMUL_TILE_576x32;
using ::CUBLASLT_MATMUL_TILE_576x40;
using ::CUBLASLT_MATMUL_TILE_576x48;
using ::CUBLASLT_MATMUL_TILE_576x56;
using ::CUBLASLT_MATMUL_TILE_576x64;
using ::CUBLASLT_MATMUL_TILE_576x72;
using ::CUBLASLT_MATMUL_TILE_576x8;
using ::CUBLASLT_MATMUL_TILE_576x80;
using ::CUBLASLT_MATMUL_TILE_576x88;
using ::CUBLASLT_MATMUL_TILE_576x96;
using ::CUBLASLT_MATMUL_TILE_584x64;
using ::CUBLASLT_MATMUL_TILE_592x64;
using ::CUBLASLT_MATMUL_TILE_600x64;
using ::CUBLASLT_MATMUL_TILE_608x64;
using ::CUBLASLT_MATMUL_TILE_616x64;
using ::CUBLASLT_MATMUL_TILE_624x64;
using ::CUBLASLT_MATMUL_TILE_632x64;
using ::CUBLASLT_MATMUL_TILE_640x16;
using ::CUBLASLT_MATMUL_TILE_640x24;
using ::CUBLASLT_MATMUL_TILE_640x32;
using ::CUBLASLT_MATMUL_TILE_640x40;
using ::CUBLASLT_MATMUL_TILE_640x48;
using ::CUBLASLT_MATMUL_TILE_640x56;
using ::CUBLASLT_MATMUL_TILE_640x64;
using ::CUBLASLT_MATMUL_TILE_640x72;
using ::CUBLASLT_MATMUL_TILE_640x8;
using ::CUBLASLT_MATMUL_TILE_640x80;
using ::CUBLASLT_MATMUL_TILE_640x88;
using ::CUBLASLT_MATMUL_TILE_640x96;
using ::CUBLASLT_MATMUL_TILE_648x64;
using ::CUBLASLT_MATMUL_TILE_64x104;
using ::CUBLASLT_MATMUL_TILE_64x112;
using ::CUBLASLT_MATMUL_TILE_64x120;
using ::CUBLASLT_MATMUL_TILE_64x128;
using ::CUBLASLT_MATMUL_TILE_64x136;
using ::CUBLASLT_MATMUL_TILE_64x144;
using ::CUBLASLT_MATMUL_TILE_64x152;
using ::CUBLASLT_MATMUL_TILE_64x16;
using ::CUBLASLT_MATMUL_TILE_64x160;
using ::CUBLASLT_MATMUL_TILE_64x168;
using ::CUBLASLT_MATMUL_TILE_64x176;
using ::CUBLASLT_MATMUL_TILE_64x184;
using ::CUBLASLT_MATMUL_TILE_64x192;
using ::CUBLASLT_MATMUL_TILE_64x200;
using ::CUBLASLT_MATMUL_TILE_64x208;
using ::CUBLASLT_MATMUL_TILE_64x216;
using ::CUBLASLT_MATMUL_TILE_64x224;
using ::CUBLASLT_MATMUL_TILE_64x232;
using ::CUBLASLT_MATMUL_TILE_64x24;
using ::CUBLASLT_MATMUL_TILE_64x240;
using ::CUBLASLT_MATMUL_TILE_64x248;
using ::CUBLASLT_MATMUL_TILE_64x256;
using ::CUBLASLT_MATMUL_TILE_64x264;
using ::CUBLASLT_MATMUL_TILE_64x272;
using ::CUBLASLT_MATMUL_TILE_64x280;
using ::CUBLASLT_MATMUL_TILE_64x288;
using ::CUBLASLT_MATMUL_TILE_64x296;
using ::CUBLASLT_MATMUL_TILE_64x304;
using ::CUBLASLT_MATMUL_TILE_64x312;
using ::CUBLASLT_MATMUL_TILE_64x32;
using ::CUBLASLT_MATMUL_TILE_64x320;
using ::CUBLASLT_MATMUL_TILE_64x328;
using ::CUBLASLT_MATMUL_TILE_64x336;
using ::CUBLASLT_MATMUL_TILE_64x344;
using ::CUBLASLT_MATMUL_TILE_64x352;
using ::CUBLASLT_MATMUL_TILE_64x360;
using ::CUBLASLT_MATMUL_TILE_64x368;
using ::CUBLASLT_MATMUL_TILE_64x376;
using ::CUBLASLT_MATMUL_TILE_64x384;
using ::CUBLASLT_MATMUL_TILE_64x392;
using ::CUBLASLT_MATMUL_TILE_64x40;
using ::CUBLASLT_MATMUL_TILE_64x400;
using ::CUBLASLT_MATMUL_TILE_64x408;
using ::CUBLASLT_MATMUL_TILE_64x416;
using ::CUBLASLT_MATMUL_TILE_64x424;
using ::CUBLASLT_MATMUL_TILE_64x432;
using ::CUBLASLT_MATMUL_TILE_64x440;
using ::CUBLASLT_MATMUL_TILE_64x448;
using ::CUBLASLT_MATMUL_TILE_64x456;
using ::CUBLASLT_MATMUL_TILE_64x464;
using ::CUBLASLT_MATMUL_TILE_64x472;
using ::CUBLASLT_MATMUL_TILE_64x48;
using ::CUBLASLT_MATMUL_TILE_64x480;
using ::CUBLASLT_MATMUL_TILE_64x488;
using ::CUBLASLT_MATMUL_TILE_64x496;
using ::CUBLASLT_MATMUL_TILE_64x504;
using ::CUBLASLT_MATMUL_TILE_64x512;
using ::CUBLASLT_MATMUL_TILE_64x520;
using ::CUBLASLT_MATMUL_TILE_64x528;
using ::CUBLASLT_MATMUL_TILE_64x536;
using ::CUBLASLT_MATMUL_TILE_64x544;
using ::CUBLASLT_MATMUL_TILE_64x552;
using ::CUBLASLT_MATMUL_TILE_64x56;
using ::CUBLASLT_MATMUL_TILE_64x560;
using ::CUBLASLT_MATMUL_TILE_64x568;
using ::CUBLASLT_MATMUL_TILE_64x576;
using ::CUBLASLT_MATMUL_TILE_64x584;
using ::CUBLASLT_MATMUL_TILE_64x592;
using ::CUBLASLT_MATMUL_TILE_64x600;
using ::CUBLASLT_MATMUL_TILE_64x608;
using ::CUBLASLT_MATMUL_TILE_64x616;
using ::CUBLASLT_MATMUL_TILE_64x624;
using ::CUBLASLT_MATMUL_TILE_64x632;
using ::CUBLASLT_MATMUL_TILE_64x64;
using ::CUBLASLT_MATMUL_TILE_64x640;
using ::CUBLASLT_MATMUL_TILE_64x648;
using ::CUBLASLT_MATMUL_TILE_64x656;
using ::CUBLASLT_MATMUL_TILE_64x664;
using ::CUBLASLT_MATMUL_TILE_64x672;
using ::CUBLASLT_MATMUL_TILE_64x680;
using ::CUBLASLT_MATMUL_TILE_64x688;
using ::CUBLASLT_MATMUL_TILE_64x696;
using ::CUBLASLT_MATMUL_TILE_64x704;
using ::CUBLASLT_MATMUL_TILE_64x712;
using ::CUBLASLT_MATMUL_TILE_64x72;
using ::CUBLASLT_MATMUL_TILE_64x720;
using ::CUBLASLT_MATMUL_TILE_64x728;
using ::CUBLASLT_MATMUL_TILE_64x736;
using ::CUBLASLT_MATMUL_TILE_64x744;
using ::CUBLASLT_MATMUL_TILE_64x752;
using ::CUBLASLT_MATMUL_TILE_64x760;
using ::CUBLASLT_MATMUL_TILE_64x768;
using ::CUBLASLT_MATMUL_TILE_64x8;
using ::CUBLASLT_MATMUL_TILE_64x80;
using ::CUBLASLT_MATMUL_TILE_64x88;
using ::CUBLASLT_MATMUL_TILE_64x96;
using ::CUBLASLT_MATMUL_TILE_656x64;
using ::CUBLASLT_MATMUL_TILE_664x64;
using ::CUBLASLT_MATMUL_TILE_672x64;
using ::CUBLASLT_MATMUL_TILE_680x64;
using ::CUBLASLT_MATMUL_TILE_688x64;
using ::CUBLASLT_MATMUL_TILE_696x64;
using ::CUBLASLT_MATMUL_TILE_704x16;
using ::CUBLASLT_MATMUL_TILE_704x24;
using ::CUBLASLT_MATMUL_TILE_704x32;
using ::CUBLASLT_MATMUL_TILE_704x40;
using ::CUBLASLT_MATMUL_TILE_704x48;
using ::CUBLASLT_MATMUL_TILE_704x56;
using ::CUBLASLT_MATMUL_TILE_704x64;
using ::CUBLASLT_MATMUL_TILE_704x72;
using ::CUBLASLT_MATMUL_TILE_704x8;
using ::CUBLASLT_MATMUL_TILE_704x80;
using ::CUBLASLT_MATMUL_TILE_704x88;
using ::CUBLASLT_MATMUL_TILE_712x64;
using ::CUBLASLT_MATMUL_TILE_720x64;
using ::CUBLASLT_MATMUL_TILE_728x64;
using ::CUBLASLT_MATMUL_TILE_72x128;
using ::CUBLASLT_MATMUL_TILE_72x192;
using ::CUBLASLT_MATMUL_TILE_72x256;
using ::CUBLASLT_MATMUL_TILE_72x320;
using ::CUBLASLT_MATMUL_TILE_72x384;
using ::CUBLASLT_MATMUL_TILE_72x448;
using ::CUBLASLT_MATMUL_TILE_72x512;
using ::CUBLASLT_MATMUL_TILE_72x576;
using ::CUBLASLT_MATMUL_TILE_72x64;
using ::CUBLASLT_MATMUL_TILE_72x640;
using ::CUBLASLT_MATMUL_TILE_736x64;
using ::CUBLASLT_MATMUL_TILE_744x64;
using ::CUBLASLT_MATMUL_TILE_752x64;
using ::CUBLASLT_MATMUL_TILE_760x64;
using ::CUBLASLT_MATMUL_TILE_768x16;
using ::CUBLASLT_MATMUL_TILE_768x24;
using ::CUBLASLT_MATMUL_TILE_768x32;
using ::CUBLASLT_MATMUL_TILE_768x40;
using ::CUBLASLT_MATMUL_TILE_768x48;
using ::CUBLASLT_MATMUL_TILE_768x56;
using ::CUBLASLT_MATMUL_TILE_768x64;
using ::CUBLASLT_MATMUL_TILE_768x72;
using ::CUBLASLT_MATMUL_TILE_768x8;
using ::CUBLASLT_MATMUL_TILE_768x80;
using ::CUBLASLT_MATMUL_TILE_80x128;
using ::CUBLASLT_MATMUL_TILE_80x192;
using ::CUBLASLT_MATMUL_TILE_80x256;
using ::CUBLASLT_MATMUL_TILE_80x320;
using ::CUBLASLT_MATMUL_TILE_80x384;
using ::CUBLASLT_MATMUL_TILE_80x448;
using ::CUBLASLT_MATMUL_TILE_80x512;
using ::CUBLASLT_MATMUL_TILE_80x576;
using ::CUBLASLT_MATMUL_TILE_80x64;
using ::CUBLASLT_MATMUL_TILE_88x128;
using ::CUBLASLT_MATMUL_TILE_88x192;
using ::CUBLASLT_MATMUL_TILE_88x256;
using ::CUBLASLT_MATMUL_TILE_88x320;
using ::CUBLASLT_MATMUL_TILE_88x384;
using ::CUBLASLT_MATMUL_TILE_88x448;
using ::CUBLASLT_MATMUL_TILE_88x512;
using ::CUBLASLT_MATMUL_TILE_88x64;
using ::CUBLASLT_MATMUL_TILE_8x128;
using ::CUBLASLT_MATMUL_TILE_8x16;
using ::CUBLASLT_MATMUL_TILE_8x192;
using ::CUBLASLT_MATMUL_TILE_8x256;
using ::CUBLASLT_MATMUL_TILE_8x32;
using ::CUBLASLT_MATMUL_TILE_8x320;
using ::CUBLASLT_MATMUL_TILE_8x384;
using ::CUBLASLT_MATMUL_TILE_8x448;
using ::CUBLASLT_MATMUL_TILE_8x512;
using ::CUBLASLT_MATMUL_TILE_8x576;
using ::CUBLASLT_MATMUL_TILE_8x64;
using ::CUBLASLT_MATMUL_TILE_8x640;
using ::CUBLASLT_MATMUL_TILE_8x704;
using ::CUBLASLT_MATMUL_TILE_8x768;
using ::CUBLASLT_MATMUL_TILE_8x8;
using ::CUBLASLT_MATMUL_TILE_96x128;
using ::CUBLASLT_MATMUL_TILE_96x192;
using ::CUBLASLT_MATMUL_TILE_96x256;
using ::CUBLASLT_MATMUL_TILE_96x320;
using ::CUBLASLT_MATMUL_TILE_96x384;
using ::CUBLASLT_MATMUL_TILE_96x448;
using ::CUBLASLT_MATMUL_TILE_96x512;
using ::CUBLASLT_MATMUL_TILE_96x64;
using ::CUBLASLT_MATMUL_TILE_END;
using ::CUBLASLT_MATMUL_TILE_UNDEFINED;
using ::cublasLtMatmulTile_t;

// ========================================================================
// Enumerations: cublasLtMatmulStages_t
// ========================================================================
using ::CUBLASLT_MATMUL_STAGES_128x1;
using ::CUBLASLT_MATMUL_STAGES_128x2;
using ::CUBLASLT_MATMUL_STAGES_128x3;
using ::CUBLASLT_MATMUL_STAGES_128x4;
using ::CUBLASLT_MATMUL_STAGES_128x5;
using ::CUBLASLT_MATMUL_STAGES_128x6;
using ::CUBLASLT_MATMUL_STAGES_128xAUTO;
using ::CUBLASLT_MATMUL_STAGES_16x1;
using ::CUBLASLT_MATMUL_STAGES_16x10;
using ::CUBLASLT_MATMUL_STAGES_16x2;
using ::CUBLASLT_MATMUL_STAGES_16x3;
using ::CUBLASLT_MATMUL_STAGES_16x4;
using ::CUBLASLT_MATMUL_STAGES_16x5;
using ::CUBLASLT_MATMUL_STAGES_16x6;
using ::CUBLASLT_MATMUL_STAGES_16xAUTO;
using ::CUBLASLT_MATMUL_STAGES_256xAUTO;
using ::CUBLASLT_MATMUL_STAGES_32x1;
using ::CUBLASLT_MATMUL_STAGES_32x10;
using ::CUBLASLT_MATMUL_STAGES_32x2;
using ::CUBLASLT_MATMUL_STAGES_32x3;
using ::CUBLASLT_MATMUL_STAGES_32x4;
using ::CUBLASLT_MATMUL_STAGES_32x5;
using ::CUBLASLT_MATMUL_STAGES_32x6;
using ::CUBLASLT_MATMUL_STAGES_32xAUTO;
using ::CUBLASLT_MATMUL_STAGES_64x1;
using ::CUBLASLT_MATMUL_STAGES_64x2;
using ::CUBLASLT_MATMUL_STAGES_64x3;
using ::CUBLASLT_MATMUL_STAGES_64x4;
using ::CUBLASLT_MATMUL_STAGES_64x5;
using ::CUBLASLT_MATMUL_STAGES_64x6;
using ::CUBLASLT_MATMUL_STAGES_64xAUTO;
using ::CUBLASLT_MATMUL_STAGES_8x3;
using ::CUBLASLT_MATMUL_STAGES_8x4;
using ::CUBLASLT_MATMUL_STAGES_8x5;
using ::CUBLASLT_MATMUL_STAGES_8xAUTO;
using ::CUBLASLT_MATMUL_STAGES_END;
using ::CUBLASLT_MATMUL_STAGES_UNDEFINED;
using ::cublasLtMatmulStages_t;

// ========================================================================
// Enumerations: cublasLtClusterShape_t
// ========================================================================
using ::CUBLASLT_CLUSTER_SHAPE_10x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_11x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_12x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_13x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_14x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_15x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_16x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x10x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x11x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x12x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x13x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x14x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x15x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x16x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x2x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x3x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x4x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x5x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x6x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x7x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x8x1;
using ::CUBLASLT_CLUSTER_SHAPE_1x9x1;
using ::CUBLASLT_CLUSTER_SHAPE_2x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_2x2x1;
using ::CUBLASLT_CLUSTER_SHAPE_2x3x1;
using ::CUBLASLT_CLUSTER_SHAPE_2x4x1;
using ::CUBLASLT_CLUSTER_SHAPE_2x5x1;
using ::CUBLASLT_CLUSTER_SHAPE_2x6x1;
using ::CUBLASLT_CLUSTER_SHAPE_2x7x1;
using ::CUBLASLT_CLUSTER_SHAPE_2x8x1;
using ::CUBLASLT_CLUSTER_SHAPE_3x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_3x2x1;
using ::CUBLASLT_CLUSTER_SHAPE_3x3x1;
using ::CUBLASLT_CLUSTER_SHAPE_3x4x1;
using ::CUBLASLT_CLUSTER_SHAPE_3x5x1;
using ::CUBLASLT_CLUSTER_SHAPE_4x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_4x2x1;
using ::CUBLASLT_CLUSTER_SHAPE_4x3x1;
using ::CUBLASLT_CLUSTER_SHAPE_4x4x1;
using ::CUBLASLT_CLUSTER_SHAPE_5x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_5x2x1;
using ::CUBLASLT_CLUSTER_SHAPE_5x3x1;
using ::CUBLASLT_CLUSTER_SHAPE_6x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_6x2x1;
using ::CUBLASLT_CLUSTER_SHAPE_7x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_7x2x1;
using ::CUBLASLT_CLUSTER_SHAPE_8x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_8x2x1;
using ::CUBLASLT_CLUSTER_SHAPE_9x1x1;
using ::CUBLASLT_CLUSTER_SHAPE_AUTO;
using ::CUBLASLT_CLUSTER_SHAPE_END;
using ::cublasLtClusterShape_t;

// ========================================================================
// Enumerations: cublasLtMatmulInnerShape_t
// ========================================================================
using ::CUBLASLT_MATMUL_INNER_SHAPE_END;
using ::CUBLASLT_MATMUL_INNER_SHAPE_MMA16816;
using ::CUBLASLT_MATMUL_INNER_SHAPE_MMA1684;
using ::CUBLASLT_MATMUL_INNER_SHAPE_MMA1688;
using ::CUBLASLT_MATMUL_INNER_SHAPE_MMA884;
using ::CUBLASLT_MATMUL_INNER_SHAPE_UNDEFINED;
using ::cublasLtMatmulInnerShape_t;

// ========================================================================
// Enumerations: cublasLtMatmulMatrixScale_t
// ========================================================================
using ::CUBLASLT_MATMUL_MATRIX_SCALE_BLK128x128_32F;
using ::CUBLASLT_MATMUL_MATRIX_SCALE_END;
using ::CUBLASLT_MATMUL_MATRIX_SCALE_OUTER_VEC_32F;
using ::CUBLASLT_MATMUL_MATRIX_SCALE_SCALAR_32F;
using ::CUBLASLT_MATMUL_MATRIX_SCALE_VEC128_32F;
using ::CUBLASLT_MATMUL_MATRIX_SCALE_VEC16_UE4M3;
using ::CUBLASLT_MATMUL_MATRIX_SCALE_VEC32_UE8M0;
using ::cublasLtMatmulMatrixScale_t;

// ========================================================================
// Enumerations: cublasLtPointerMode_t
// ========================================================================
using ::CUBLASLT_POINTER_MODE_ALPHA_DEVICE_VECTOR_BETA_HOST;
using ::CUBLASLT_POINTER_MODE_ALPHA_DEVICE_VECTOR_BETA_ZERO;
using ::CUBLASLT_POINTER_MODE_DEVICE;
using ::CUBLASLT_POINTER_MODE_DEVICE_VECTOR;
using ::CUBLASLT_POINTER_MODE_HOST;
using ::cublasLtPointerMode_t;

// ========================================================================
// Enumerations: cublasLtPointerModeMask_t
// ========================================================================
using ::CUBLASLT_POINTER_MODE_MASK_ALPHA_DEVICE_VECTOR_BETA_HOST;
using ::CUBLASLT_POINTER_MODE_MASK_ALPHA_DEVICE_VECTOR_BETA_ZERO;
using ::CUBLASLT_POINTER_MODE_MASK_DEVICE;
using ::CUBLASLT_POINTER_MODE_MASK_DEVICE_VECTOR;
using ::CUBLASLT_POINTER_MODE_MASK_HOST;
using ::cublasLtPointerModeMask_t;

// ========================================================================
// Enumerations: cublasLtOrder_t
// ========================================================================
using ::CUBLASLT_ORDER_COL;
using ::CUBLASLT_ORDER_COL32;
using ::CUBLASLT_ORDER_COL32_2R_4R4;
using ::CUBLASLT_ORDER_COL4_4R2_8C;
using ::CUBLASLT_ORDER_ROW;
using ::cublasLtOrder_t;

// ========================================================================
// Enumerations: cublasLtBatchMode_t
// ========================================================================
using ::CUBLASLT_BATCH_MODE_POINTER_ARRAY;
using ::CUBLASLT_BATCH_MODE_STRIDED;
using ::cublasLtBatchMode_t;

// ========================================================================
// Enumerations: cublasLtMatrixLayoutAttribute_t
// ========================================================================
using ::CUBLASLT_MATRIX_LAYOUT_BATCH_COUNT;
using ::CUBLASLT_MATRIX_LAYOUT_BATCH_MODE;
using ::CUBLASLT_MATRIX_LAYOUT_COLS;
using ::CUBLASLT_MATRIX_LAYOUT_LD;
using ::CUBLASLT_MATRIX_LAYOUT_ORDER;
using ::CUBLASLT_MATRIX_LAYOUT_PLANE_OFFSET;
using ::CUBLASLT_MATRIX_LAYOUT_ROWS;
using ::CUBLASLT_MATRIX_LAYOUT_STRIDED_BATCH_OFFSET;
using ::CUBLASLT_MATRIX_LAYOUT_TYPE;
using ::cublasLtMatrixLayoutAttribute_t;

// ========================================================================
// Enumerations: cublasLtMatmulDescAttributes_t
// ========================================================================
using ::CUBLASLT_MATMUL_DESC_A_SCALE_MODE;
using ::CUBLASLT_MATMUL_DESC_A_SCALE_POINTER;
using ::CUBLASLT_MATMUL_DESC_ALPHA_VECTOR_BATCH_STRIDE;
using ::CUBLASLT_MATMUL_DESC_AMAX_D_POINTER;
using ::CUBLASLT_MATMUL_DESC_B_SCALE_MODE;
using ::CUBLASLT_MATMUL_DESC_B_SCALE_POINTER;
using ::CUBLASLT_MATMUL_DESC_BIAS_BATCH_STRIDE;
using ::CUBLASLT_MATMUL_DESC_BIAS_DATA_TYPE;
using ::CUBLASLT_MATMUL_DESC_BIAS_POINTER;
using ::CUBLASLT_MATMUL_DESC_C_SCALE_MODE;
using ::CUBLASLT_MATMUL_DESC_C_SCALE_POINTER;
using ::CUBLASLT_MATMUL_DESC_COMPUTE_TYPE;
using ::CUBLASLT_MATMUL_DESC_D_OUT_SCALE_MODE;
using ::CUBLASLT_MATMUL_DESC_D_OUT_SCALE_POINTER;
using ::CUBLASLT_MATMUL_DESC_D_SCALE_MODE;
using ::CUBLASLT_MATMUL_DESC_D_SCALE_POINTER;
using ::CUBLASLT_MATMUL_DESC_EPILOGUE;
using ::CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_AMAX_POINTER;
using ::CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_BATCH_STRIDE;
using ::CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_DATA_TYPE;
using ::CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_LD;
using ::CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_POINTER;
using ::CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_SCALE_MODE;
using ::CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_SCALE_POINTER;
using ::CUBLASLT_MATMUL_DESC_FAST_ACCUM;
using ::CUBLASLT_MATMUL_DESC_FILL_MODE;
using ::CUBLASLT_MATMUL_DESC_POINTER_MODE;
using ::CUBLASLT_MATMUL_DESC_SCALE_TYPE;
using ::CUBLASLT_MATMUL_DESC_SM_COUNT_TARGET;
using ::CUBLASLT_MATMUL_DESC_TRANSA;
using ::CUBLASLT_MATMUL_DESC_TRANSB;
using ::CUBLASLT_MATMUL_DESC_TRANSC;
using ::cublasLtMatmulDescAttributes_t;

// ========================================================================
// Enumerations: cublasLtMatrixTransformDescAttributes_t
// ========================================================================
using ::CUBLASLT_MATRIX_TRANSFORM_DESC_POINTER_MODE;
using ::CUBLASLT_MATRIX_TRANSFORM_DESC_SCALE_TYPE;
using ::CUBLASLT_MATRIX_TRANSFORM_DESC_TRANSA;
using ::CUBLASLT_MATRIX_TRANSFORM_DESC_TRANSB;
using ::cublasLtMatrixTransformDescAttributes_t;

// ========================================================================
// Enumerations: cublasLtReductionScheme_t
// ========================================================================
using ::CUBLASLT_REDUCTION_SCHEME_COMPUTE_TYPE;
using ::CUBLASLT_REDUCTION_SCHEME_INPLACE;
using ::CUBLASLT_REDUCTION_SCHEME_MASK;
using ::CUBLASLT_REDUCTION_SCHEME_NONE;
using ::CUBLASLT_REDUCTION_SCHEME_OUTPUT_TYPE;
using ::cublasLtReductionScheme_t;

// ========================================================================
// Enumerations: cublasLtEpilogue_t
// ========================================================================
using ::CUBLASLT_EPILOGUE_BGRADA;
using ::CUBLASLT_EPILOGUE_BGRADB;
using ::CUBLASLT_EPILOGUE_BIAS;
using ::CUBLASLT_EPILOGUE_DEFAULT;
using ::CUBLASLT_EPILOGUE_DGELU;
using ::CUBLASLT_EPILOGUE_DGELU_BGRAD;
using ::CUBLASLT_EPILOGUE_DRELU;
using ::CUBLASLT_EPILOGUE_DRELU_BGRAD;
using ::CUBLASLT_EPILOGUE_GELU;
using ::CUBLASLT_EPILOGUE_GELU_AUX;
using ::CUBLASLT_EPILOGUE_GELU_AUX_BIAS;
using ::CUBLASLT_EPILOGUE_GELU_BIAS;
using ::CUBLASLT_EPILOGUE_RELU;
using ::CUBLASLT_EPILOGUE_RELU_AUX;
using ::CUBLASLT_EPILOGUE_RELU_AUX_BIAS;
using ::CUBLASLT_EPILOGUE_RELU_BIAS;
using ::cublasLtEpilogue_t;

// ========================================================================
// Enumerations: cublasLtMatmulSearch_t
// ========================================================================
using ::CUBLASLT_SEARCH_BEST_FIT;
using ::CUBLASLT_SEARCH_LIMITED_BY_ALGO_ID;
using ::CUBLASLT_SEARCH_RESERVED_02;
using ::CUBLASLT_SEARCH_RESERVED_03;
using ::CUBLASLT_SEARCH_RESERVED_04;
using ::CUBLASLT_SEARCH_RESERVED_05;
using ::CUBLASLT_SEARCH_RESERVED_06;
using ::CUBLASLT_SEARCH_RESERVED_07;
using ::CUBLASLT_SEARCH_RESERVED_08;
using ::CUBLASLT_SEARCH_RESERVED_09;
using ::cublasLtMatmulSearch_t;

// ========================================================================
// Enumerations: cublasLtMatmulPreferenceAttributes_t
// ========================================================================
using ::CUBLASLT_MATMUL_PREF_IMPL_MASK;
using ::CUBLASLT_MATMUL_PREF_MAX_WAVES_COUNT;
using ::CUBLASLT_MATMUL_PREF_MAX_WORKSPACE_BYTES;
using ::CUBLASLT_MATMUL_PREF_MIN_ALIGNMENT_A_BYTES;
using ::CUBLASLT_MATMUL_PREF_MIN_ALIGNMENT_B_BYTES;
using ::CUBLASLT_MATMUL_PREF_MIN_ALIGNMENT_C_BYTES;
using ::CUBLASLT_MATMUL_PREF_MIN_ALIGNMENT_D_BYTES;
using ::CUBLASLT_MATMUL_PREF_REDUCTION_SCHEME_MASK;
using ::CUBLASLT_MATMUL_PREF_SEARCH_MODE;
using ::cublasLtMatmulPreferenceAttributes_t;

// ========================================================================
// Enumerations: cublasLtMatmulAlgoCapAttributes_t
// ========================================================================
using ::CUBLASLT_ALGO_CAP_CTA_SWIZZLING_SUPPORT;
using ::CUBLASLT_ALGO_CAP_CUSTOM_MEMORY_ORDER;
using ::CUBLASLT_ALGO_CAP_CUSTOM_OPTION_MAX;
using ::CUBLASLT_ALGO_CAP_EPILOGUE_MASK;
using ::CUBLASLT_ALGO_CAP_FLOATING_POINT_EMULATION_SUPPORT;
using ::CUBLASLT_ALGO_CAP_LD_NEGATIVE;
using ::CUBLASLT_ALGO_CAP_MIN_ALIGNMENT_A_BYTES;
using ::CUBLASLT_ALGO_CAP_MIN_ALIGNMENT_B_BYTES;
using ::CUBLASLT_ALGO_CAP_MIN_ALIGNMENT_C_BYTES;
using ::CUBLASLT_ALGO_CAP_MIN_ALIGNMENT_D_BYTES;
using ::CUBLASLT_ALGO_CAP_NUMERICAL_IMPL_FLAGS;
using ::CUBLASLT_ALGO_CAP_OUT_OF_PLACE_RESULT_SUPPORT;
using ::CUBLASLT_ALGO_CAP_POINTER_ARRAY_BATCH_SUPPORT;
using ::CUBLASLT_ALGO_CAP_POINTER_MODE_MASK;
using ::CUBLASLT_ALGO_CAP_REDUCTION_SCHEME_MASK;
using ::CUBLASLT_ALGO_CAP_SPLITK_SUPPORT;
using ::CUBLASLT_ALGO_CAP_STAGES_IDS;
using ::CUBLASLT_ALGO_CAP_STRIDED_BATCH_SUPPORT;
using ::CUBLASLT_ALGO_CAP_TILE_IDS;
using ::CUBLASLT_ALGO_CAP_UPLO_SUPPORT;
using ::cublasLtMatmulAlgoCapAttributes_t;

// ========================================================================
// Enumerations: cublasLtMatmulAlgoConfigAttributes_t
// ========================================================================
using ::CUBLASLT_ALGO_CONFIG_CLUSTER_SHAPE_ID;
using ::CUBLASLT_ALGO_CONFIG_CTA_SWIZZLING;
using ::CUBLASLT_ALGO_CONFIG_CUSTOM_OPTION;
using ::CUBLASLT_ALGO_CONFIG_ID;
using ::CUBLASLT_ALGO_CONFIG_INNER_SHAPE_ID;
using ::CUBLASLT_ALGO_CONFIG_REDUCTION_SCHEME;
using ::CUBLASLT_ALGO_CONFIG_SPLITK_NUM;
using ::CUBLASLT_ALGO_CONFIG_STAGES_ID;
using ::CUBLASLT_ALGO_CONFIG_TILE_ID;
using ::cublasLtMatmulAlgoConfigAttributes_t;

// ========================================================================
// Result struct
// ========================================================================
using ::cublasLtMatmulHeuristicResult_t;

// ========================================================================
// Logger callback type
// ========================================================================
using ::cublasLtLoggerCallback_t;

// ========================================================================
// Context management functions
// ========================================================================
using ::cublasLtCreate;
using ::cublasLtDestroy;
using ::cublasLtDisableCpuInstructionsSetMask;
using ::cublasLtGetCudartVersion;
using ::cublasLtGetProperty;
using ::cublasLtGetStatusName;
using ::cublasLtGetStatusString;
using ::cublasLtGetVersion;
using ::cublasLtHeuristicsCacheGetCapacity;
using ::cublasLtHeuristicsCacheSetCapacity;

// ========================================================================
// Core computation functions
// ========================================================================
using ::cublasLtMatmul;
using ::cublasLtMatrixTransform;

// ========================================================================
// Matrix layout descriptor functions
// ========================================================================
using ::cublasLtMatrixLayoutCreate;
using ::cublasLtMatrixLayoutDestroy;
using ::cublasLtMatrixLayoutGetAttribute;
using ::cublasLtMatrixLayoutInit_internal;
using ::cublasLtMatrixLayoutSetAttribute;

// Inline init helper (wraps _internal)
inline cublasStatus_t cublasLtMatrixLayoutInit(cublasLtMatrixLayout_t matLayout, cudaDataType type,
                                               uint64_t rows, uint64_t cols, int64_t ld) {
  return ::cublasLtMatrixLayoutInit_internal(matLayout, sizeof(*matLayout), type, rows, cols, ld);
}

// ========================================================================
// Matmul descriptor functions
// ========================================================================
using ::cublasLtMatmulDescCreate;
using ::cublasLtMatmulDescDestroy;
using ::cublasLtMatmulDescGetAttribute;
using ::cublasLtMatmulDescInit_internal;
using ::cublasLtMatmulDescSetAttribute;

// Inline init helper (wraps _internal)
inline cublasStatus_t cublasLtMatmulDescInit(cublasLtMatmulDesc_t matmulDesc,
                                             cublasComputeType_t computeType,
                                             cudaDataType_t scaleType) {
  return ::cublasLtMatmulDescInit_internal(matmulDesc, sizeof(*matmulDesc), computeType, scaleType);
}

// ========================================================================
// Matrix transform descriptor functions
// ========================================================================
using ::cublasLtMatrixTransformDescCreate;
using ::cublasLtMatrixTransformDescDestroy;
using ::cublasLtMatrixTransformDescGetAttribute;
using ::cublasLtMatrixTransformDescInit_internal;
using ::cublasLtMatrixTransformDescSetAttribute;

// Inline init helper (wraps _internal)
inline cublasStatus_t cublasLtMatrixTransformDescInit(cublasLtMatrixTransformDesc_t transformDesc,
                                                      cudaDataType scaleType) {
  return ::cublasLtMatrixTransformDescInit_internal(transformDesc, sizeof(*transformDesc),
                                                    scaleType);
}

// ========================================================================
// Matmul preference descriptor functions
// ========================================================================
using ::cublasLtMatmulPreferenceCreate;
using ::cublasLtMatmulPreferenceDestroy;
using ::cublasLtMatmulPreferenceGetAttribute;
using ::cublasLtMatmulPreferenceInit_internal;
using ::cublasLtMatmulPreferenceSetAttribute;

// Inline init helper (wraps _internal)
inline cublasStatus_t cublasLtMatmulPreferenceInit(cublasLtMatmulPreference_t pref) {
  return ::cublasLtMatmulPreferenceInit_internal(pref, sizeof(*pref));
}

// ========================================================================
// Heuristic and algorithm functions
// ========================================================================
using ::cublasLtMatmulAlgoCapGetAttribute;
using ::cublasLtMatmulAlgoCheck;
using ::cublasLtMatmulAlgoConfigGetAttribute;
using ::cublasLtMatmulAlgoConfigSetAttribute;
using ::cublasLtMatmulAlgoGetHeuristic;
using ::cublasLtMatmulAlgoGetIds;
using ::cublasLtMatmulAlgoInit;

// ========================================================================
// Logger functions
// ========================================================================
using ::cublasLtLoggerForceDisable;
using ::cublasLtLoggerOpenFile;
using ::cublasLtLoggerSetCallback;
using ::cublasLtLoggerSetFile;
using ::cublasLtLoggerSetLevel;
using ::cublasLtLoggerSetMask;

} // namespace wwr::cuda
